### ISSUE TITLE
[AlphaTab][API] An unexpected error occurred TypeError: right-hand side of 'in' should be an object, got undefined

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting an API error in AlphaTab.

I have searched and previously noted this issue, however if you aren't logged into GitHub, and try to file an issue, the system only offers "Issue" as the only choice for a repository.

While there is playback, and all functions work, such as Play, Stop etc., there is no rendering of notation. In addition, there is an access violation in Chrome.

### Expected Behavior

Rendering should occur

### Steps To Reproduce

- Navigate to page in question
- See that rendering has not occured
- Press play and stop to confirm .gp file has loaded and playback can occur
- Open browser console to verify error

### Link to jsFiddle, CodePen, Project

https://www.emotive.productions/notation/love-and-fear/player/

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: Windows
- **Browser**: Firefox and Chrome
```

### Anything else?

alphaTab v1.3.0-alpha.411 (develop, build 411)

**Comment by Danielku15** [comment]
This is not a bug in alphaTab but in your code. You are calling alphaTab with like `api.changeTrackMute([undefined], true)` which is not valid. Here the proof: 

![image](https://user-images.githubusercontent.com/674916/194380671-b49081bc-ef4e-4366-a58d-bebb3124a844.png)

The tracks parameter has to contain proper data otherwise this can lead to unexpected errors.
