### ISSUE TITLE
Vibrato does not play for more than one bar

### ISSUE THREAD

**Issue by MrDrone-ru** [CoderLine/alphaTab#1011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The vibrato stops at the end of the bar, then one note from the vibrato range plays, not necessarily the base one.

### Expected Behavior

Vibrato for the entire duration of the note.

### Steps To Reproduce

Play a vibrating note, which consists of 2 or more notes linked through a bar.
4-5 bars in my example

### Link to jsFiddle, CodePen, Project

http://dronx.byethost16.com/attest.html

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
Opera 91.0.4516.16
```

### Anything else?

Also I wanted to change the vibrato option via code: 
```
const settings = {
                    file: ".....",
                    player: {
                        enablePlayer: true,
                        soundFont:'https://cdn.jsdelivr.net/npm/@coderline/alphatab@latest/dist/soundfont/sonivox.sf2',
                        scrollElement: wrapper.querySelector('.at-viewport'),
                        vibrato: {
                            noteSlightLength = 350
                        }
                    }
}
```
But it caused an error "Invalid shorthand property initializer"
However, this
```
api.settings.player.vibrato.noteSlightLength = 350;
api.updateSettings();
```
works fine.

**Comment by Danielku15** [comment]
In your settings object you have a syntax error. You are using an `=` sign to define values which is not valid JavaScript. You need to use a `:` there.

Regarding the bug: Actually in the GP5 file, the tied note on bar 5 has no vibrato applied, so the audio playback is correct. I double checked the binary file during reading, and there are no vibrato effects on this note. So the file reading is correct.

![image](https://user-images.githubusercontent.com/674916/195913109-3f188572-80bb-4e25-b107-b40ead5da70a.png)

It seems a bit funny that we are having the same bug like Guitar Pro in alphaTab because they also flag the tied note with a Vibrato on import:  

![image](https://user-images.githubusercontent.com/674916/195913448-b1d9eb9b-eeab-4dcf-b4f9-2841316011ea.png)

While from a file format perspective the bugfix would be correct to not show a vibrato on the tied note, I think it would be better to keep the current display and ensure the audio is generated also with a vibrato. 

What holds me a bit back to just make the change is that it could be that someone has a vibrato only on the first note, but stop at the second note.

**Comment by MrDrone-ru** [comment]
Thanks for reply.
I just thought that it would be possible to set up the behavior of AT like in Guitar Pro 5, and there the tied note plays vibrato without a sign. It probably plays the tied notes as one, and it turns out to be a bug.
Interestingly, if this file is imported into GP8, there is automatically vibrato on both notes.
