### ISSUE TITLE
Track is not played when track is selected ( a combination of live.html(old version) and play.html) 

### ISSUE THREAD

**Issue by Paopan** [CoderLine/alphaTab#104]
When I tried to combine live.html (an old alphaTab version) with play.html cut some staves options that enough for general usage (only chord, score, tablature remain), I found that track choosing is work!! However, it seems that the webworker does not update to the newly chosen track. The worker seem to play the former.

My investigation found that "tracks" variable in playerCursorUpdateTick() in jquery.alphaTab.alphaSynth.js has not been changed althouth the attribute "data-tracks" of '#alphaTab' 
was changed by the track chosen in initializeTrackChooser() in live.js.

Track selection is work!! after the combination of live.html to play.html
![Uploading Subject.jpg…]()

Unfortunately, the worker does not update to newly chosen track.
![Uploading Subject2.jpg…]()

Below is a modified  initializeTrackChooser() in live.js for your reference. 
`
function initializeTrackChooser() {
    var score = $('#alphaTab').alphaTab('score');
    var currentTrack = $('#alphaTab').alphaTab('tracks');
    currentTrack = (currentTrack.length == 0) ? null : currentTrack[0];
    var allTracks = score.Tracks;

    var list = $('#trackList');
    list.empty();
    
    for(var i = 0; i < allTracks.length; i++) 
    {
        var track = allTracks[i];
        var li = $('<li></li>');
        list.append(li);
        if(track == currentTrack) li.addClass('active');
        
        var a = $('<a></a>');
        li.append(a);
        a.attr('href', '#');
        a.text(track.Name);
        a.data('track', track);
        a.click(function(e) {
			e.preventDefault();
			console.log($("#alphaTab").attr('data-tracks'));
			$('#alphaTab').attr('data-tracks', $(this).data('track').Index);
			console.log($("#alphaTab").attr('data-tracks'));
			//$.alphaTab.restore('#alphaTab');
			//$('#alphaTab').alphaTab();
			$('#alphaTab').alphaTab('renderer').Render($(this).data('track'));
			$('#trackChooser').fadeOut();
        });
    }
	//update player
	var cursorOptions = $('#alphaTab').alphaTab('cursorOptions');
	var scrollmode = $('a[data-layout]').data('layout');
	cursorOptions.autoScroll = scrollmode;
	$('body,html').animate({
        scrollTop: 0 
    }, 300);
	$('#alphaTab').alphaTab('playerCursorUpdateBeat', cursorOptions.currentBeat);
}
`
It would be great if this combination could be achieved.
Thank you in advance for your instruction.

**Comment by Danielku15** [comment]
Hi. 
I decided to remove the live example since it was hard to maintain and also caused some troubles. For the different settings it's better to consider the features sample as reference. Anyhow the samples should only show how to achieve things using the alphaTab API, it's not meant to simply copy them for productive use.

The current version loading the tracks and changing tracks should work properly even with web worker rendering. I prepared you a small example with the current version where you can see an updated track selector in action http://demo.alphatab.net/crm/trackSelector/index.html

Does this help you in your implementation of a custom track selector?

**Comment by Paopan** [comment]
Thanks a lot Daniel sample tract selector works!!
I am trying to setup an online playable song's tablature to help musicians have an experience
of this in my country. This will surely help them to use the player more effectively.

Thanks again for your prompt response as well.

**Comment by Paopan** [comment]
For one more thing, is there any way for users to change the tempo of the song once rendered on the canvas?
Some song's original tempo might be to fast for some player to play at original speed.
Thanks in advance for your advice.

**Comment by Danielku15** [comment]
Yes, alphaSynth (the player engine) has a property for changing the playback speed but it's currently not accessible from the API.  I filed an [issue](https://github.com/CoderLine/alphaSynth/issues/3) on alphaTab side to add a dedicated API for changing the playback speed on the fly. I will close this defect since the track selector topic is closed.

**Comment by Danielku15** [comment]
The issue on alphaSynth is fixed and I updated the alphaTab player sample to show the usage of the playback speed: http://demo.alphatab.net/player.html 

You can now change the playback speed on the fly by setting in on alphaSynth.

**Comment by Paopan** [comment]
Appreciated your help always.
