### ISSUE TITLE
Two Repeat sections with alternate endings causes the second one to skip its main part

### ISSUE THREAD

**Issue by jonaro00** [CoderLine/alphaTab#1046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/54029719/202928960-bc3eecab-0f13-491f-99f5-a97958a5c59d.png)

In the piece above, the first bars play in the correct order: 1, 2, 1, 3.
But after that, the player jumps to bar 5 (skipping the first play of bar 4), to then continues to correctly play 4, 6, 4, 6, 4, 6, 7... 

Happens in both 1.2.3 and on develop branch.
Unsure if this issue is AlphaTex specific or global...

### Expected Behavior

Bar 4 should not be skipped in the first repeat lap.

### Steps To Reproduce

```tex
\tempo 175
.
\ro :1 r | \ae 1 r | \ae 2 \rc 2 r | \ro r | \ae 1 r | \ae (2 3 4) \rc 4 r | 
```

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **OS**: Windows 10
- **Browser**: Latest Brave (Chromium)
```

### Anything else?

This surprised me a lot. I wrote a piece in AlphaTex using many alternate endings while AE had been implemented but not yet released. At that time it worked as expected. When I played the piece again today I noticed this bug.

**Comment by jonaro00** [comment]
Also noticed: Shouldn't there be another repeat ending symbol in bar 2 and 5? Like in this example https://www.alphatab.net/docs/showcase/general#alternate-endings

**Comment by Danielku15** [comment]
In the 1.2.3 release I merged some bigger change related to repeats. I redeveloped completely the component handling the repeats. The old ones had some bigger flaws so I started over. 

Regarding the symbols it depends on how you write the notation, in this case it does not make a big difference because there are no additional bars after bar 6. But theoretically you could have a combination like this: 
![image](https://user-images.githubusercontent.com/674916/204088985-cdda682a-42b6-4b23-955e-3dd93087806a.png)

There with not having a repeat ending in bar 5, you can still have bars afterwards. With having a repeat end symbol at bar 5 you would directly jump back to bar 4 without this possibility. In cases like this it might be a readability thing and one might put also a repeat end on bar 5. Otherwise you need to "scan" with your eye where the next ending is to know what you need to play.
