### ISSUE TITLE
Clicking the score at a point after a repeat causes quick flash of cursor at incorrect position

### ISSUE THREAD

**Issue by jonaro00** [CoderLine/alphaTab#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/54029719/202929788-73baa121-42f7-41ba-8597-84af2671542a.png)

When clicking on bar 3, the blue beat cursor recalculates its position. During this, it (and the yellow bar highlight) flashes and is briefly visible on bar 1 (circled in image above) for roughly one frame. (I can provide a slow mo GIF if needed)

### Expected Behavior

The cursor should not render until the new position is fully calculated.

### Steps To Reproduce

```tex
\ro :1 r | \rc 2 r | r | r
```
Click repeatedly on bar 3 and see the cursor flash on bar 1.

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: Windows 10
- **Browser**: Latest Brave (Chromium) and Firefox
```

### Anything else?

Likely caused when the offset from start of score is calculated and the durations of repeats are added afterwards.

**Comment by Danielku15** [comment]
The problem is caused here: https://github.com/CoderLine/alphaTab/blob/56b444c7affbeb597bece605aee4c7f07d8057a2/src/AlphaTabApiBase.ts#L1165

We are seeking to the `absolutePlaybackStart` of the clicked beat. But this information there in the model does not respect repeats seeking actually to the bar 0 (because that's the one at played at `absolutePlaybackStart`) and then another trigger in alphaTab corrects the cursor.
