### ISSUE TITLE
about chord diagrams 

### ISSUE THREAD

**Issue by k4s** [CoderLine/alphaTab#110]
hi,can i show the chord diagrams in the website,no the chord letter?

**Comment by Danielku15** [comment]
Hi. 
At the current state AlphaTab not render any chord diagrams but most information for adding them would be available (at least since the last commits). Here an example that outputs the chord details https://jsfiddle.net/danielku15/wpyny8x0/ Maybe you can use some 3rd party chord renderer until alphaTab fully supports it. 

In near future I will likely add the chord diagrams the way Guitar Pro 6 renders them, on top of the whole music sheet:
![gp6_chords](https://cloud.githubusercontent.com/assets/674916/22627201/60081cca-ebbe-11e6-92a7-376aebd33723.png)

For rendering them directly above the beat I see some layouting challenges. Guitar Pro 5 already suffered of such problems: 

![gp5_chords](https://cloud.githubusercontent.com/assets/674916/22627207/89a17306-ebbe-11e6-8639-425d9bc93df8.png)

**Comment by Danielku15** [comment]
Update: I started with the implementation of rendering chord diagrams. Here you can see the current state: 
https://twitter.com/alphaTabMusic/status/828308020862009350

**Comment by Danielku15** [comment]
Chord diagrams are now shown with the latest changes on `develop`. I'm keeping this issue open to potentially add the display of fingerings.

**Comment by Danielku15** [comment]
Moving to next version as fingering will likely not come in this release.
