### ISSUE TITLE
Issue with .gpx files

### ISSUE THREAD

**Issue by LeadGuitarMx** [CoderLine/alphaTab#112]
Hi.. first of all I want to say thank you for your great work, I'm using this script for a while and works very good.

I just have a problem opening de .gpx files, with all the other formats is ok.

Here some examples:
GPX files:
https://leadguitar.mx/tablaturas/ver/5/
https://leadguitar.mx/tablaturas/ver/540/
https://leadguitar.mx/tablaturas/ver/1/

Other formats working OK:
https://leadguitar.mx/tablaturas/ver/69/
https://leadguitar.mx/tablaturas/ver/616/
https://leadguitar.mx/tablaturas/Eric-Clapton/Layla/

![2017-01-13](https://cloud.githubusercontent.com/assets/16194213/21952170/af5b15c8-d9d2-11e6-986a-34c7e8dd4950.png)

**Comment by Danielku15** [comment]
Hi. 
Yes, this is a known issue, I lately discovered an issue which I forgot to enter here. The problem is the usage of WebWorkers in combination with GPX files. GPX internally is an XML document, but in WebWorkers the whole DOM API is unavailable, including possible XML parsing. This would be a temporary workaround until I've sorted out how to parse XML in WebWorkers:

```javascript
var at = $('#alphaTab');
at.alphaTab({
    useWorker: at.data('file').indexOf('.gpx') > -1
}); // load alphaTab
```

**Comment by LeadGuitarMx** [comment]
OK.. I understand.. but thank you anyways!!

Cheers and keep up the good work man!
You're awesome!! .lm/
