### ISSUE TITLE
Wrapper in fullscreen cause content wrong rendering

### ISSUE THREAD

**Issue by MercierCorentin** [CoderLine/alphaTab#1145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I followed the tutorial and tried to add to add a fullscreen mode.

It put the wrapper in fullscreen mode but the content is misrendered:
![image](https://user-images.githubusercontent.com/46066895/230904660-3aae6429-9062-4186-825f-ecda093510e4.png)

### Expected Behavior

I would expect the usual nice score rendering but in fullscreen, like this:
![image](https://user-images.githubusercontent.com/46066895/230905145-e9d5b9bf-536b-4f53-9718-d43c8a3a9ab8.png)

### Steps To Reproduce

1. Copy paste final file of web tutorial into a `HTML` file: https://alphatab.net/docs/tutorial-web/player#final-file
2. Replace count-In by fullscreen:
Before:
```javascript
      countIn.onclick = () => {
        countIn.classList.toggle('active');
        if (countIn.classList.contains('active')) {
          api.countInVolume = 1;
        } else {
          api.countInVolume = 0;
        }
      };
```
After: 
```javascript
      countIn.onclick = () => {
	if (document.fullscreenElement) {
		document.exitFullscreen();
	} else {
		// Parent full screen
		wrapper.requestFullscreen();
	}
      };
```
3. Click on the countIn logo

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: Ubuntu 22.04.2 LTS
- **Browser**: Mozilla Firefox 111.0.1 and Google Chrome 111.0.5563.64
```

**Comment by Danielku15** [comment]
I had a look and alphaTab is rendering fine. The problem is outside alphaTab because elements put to full screen to not have a background color. The Music Sheet rendered by alphaTab doesn't get a background color but it is transparent. Any background color can/must be set on the outside containers. In this case the music sheet is then simply black-on-black which makes it look weird. 

It is indeed a bit strange that browser manufacturers decided to make the "full screen layer" background black by default.

https://css-tricks.com/how-to-leverage-the-fullscreen-api-and-style-it/
https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen
https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop

Hope that helps.

**Comment by MercierCorentin** [comment]
Thanks a lot for your reactivity and clear explanation, I now have a nice AlphaTab in fullscreen !
