### ISSUE TITLE
On positionChanged - bar calculation

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#115]
Hello,
I have a HTML table of bars and I need to update current playing bar. I found one event which should be fine. To calculate current bar I wrote this code:
       
            as.On("positionChanged", function (currentTime, endTime, currentTick, endTick) {
                playerApp.updateSelectedBar(currentTick);
            });

            var updateSelectedBar = function (currentTick) {

                var htmlBars = $(".row-head").find("[data-bar]");
                htmlBars.removeClass("selected");

                for (var i = 0; i < Score.MasterBars.length; i++) {
                var bar = Score.MasterBars[i];
                var nextBar = bar.NextMasterBar;
                var start = bar.Start;

                if (nextBar == null) {
                    htmlBars.eq(i).addClass("selected");
                    break;
                }

                var end = nextBar.Start;
                if (currentTick >= start && currentTick < end) {
                    htmlBars.eq(i).addClass("selected");
                    break;
                }
            }
        };

All works fine until song do not have repetition signs. Is an easy option to return current playing bar? Is there a relation between currentTick and Score.MasterBars[i].Start field or I need to do more magic in my lines? Thanks in advance for your suggestions.

Best regards,
Jarek

**Comment by Danielku15** [comment]
Hi Jarek. 

You can check how in the [alphaSynth plugin](https://github.com/CoderLine/alphaTab/blob/master/Build/JavaScript/jquery.alphaTab.alphaSynth.js) this problem is solved, There is a so called TickCache where you can very quickly lookup which beat is currently being played. This cache is created during [the midi generation](https://github.com/CoderLine/alphaTab/blob/master/Build/JavaScript/jquery.alphaTab.alphaSynth.js#L7) and properly handles all repeat cases.  

If you are using the alphaSynth plugin and interested, I could simply add a new event which is triggered whenever the played beat changes. This lookup is anyhow done to position the playback cursors.

**Comment by yaras6** [comment]
Hi,I am using alphaSync. If it is no problem please add this event. I will check tommorow how works tick cache. ThanksBest regards,Jarek16.02.2017 6:36 PM Daniel <notifications@github.com> napisał(a):Hi Jarek.
You can check how in the alphaSynth plugin this problem is solved, There is a so called TickCache where you can very quickly lookup which beat is currently being played. This cache is created during the midi generation and properly handles all repeat cases.
If you are using the alphaSynth plugin and interested, I could simply add a new event which is triggered whenever the played beat changes. This lookup is anyhow done to position the playback cursors.

**Comment by Danielku15** [comment]
I opened up the API a bit and added the new event. Here a small example where I create a list of squares for the bars and make them clickable. https://jsfiddle.net/danielku15/zvq0mm14/
Let me know if you need anything more for your usecase.

**Comment by yaras6** [comment]
Thank you very much. Example looks perfect. Tomorrow I will adapt it in my project.
