### ISSUE TITLE
The issue of using alphaTab font in reac not displaying properly

### ISSUE THREAD

**Issue by LinJiuSam** [CoderLine/alphaTab#1161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/:1 Failed to decode downloaded font: http://localhost:3000/static/js/font/Bravura.woff
2#/:1 OTS parsing error: invalid sfntVersion: 1008813135
2#/:1 Failed to decode downloaded font: http://localhost:3000/static/js/font/Bravura.otf
2#/:1 OTS parsing error: invalid sfntVersion: 1008813135
alphaTab.mjs:1284 [AlphaTab][Font] [alphaTab] Loading Failed, rendering cannot start DOMException: A network error occurred.
error @ alphaTab.mjs:1284
alphaTab.mjs:1284 [AlphaTab][Font] [alphaTab] Loading Failed, rendering cannot start Font not available
e

### Expected Behavior

The font used for alphaTab is Bravura valid sfntVersion: 1008813135

### Steps To Reproduce

Pull in AlphaTab on the NPM official website
Import {AlphaTabApi} from '@ coderline/alphatab' in the reac project;
const wrapper = document.querySelector(".at-wrap");
        const main = wrapper.querySelector(".at-main");

        // // initialize alphatab
        const settings = {
            file: "https://www.alphatab.net/files/canon.gp",
        };
        console.log(new AlphaTabApi(main, settings));

### Found in Version

1.2

### Platform

Node.js

### Environment

```markdown
- **OS**: Windows Pro
- **Browser**: Edge
```

**Comment by Danielku15** [comment]
I assume you have seen the related discussions around the support in React/Angular (well bundlers in general). If not you might want to read: 

* https://alphatab.net/docs/getting-started/installation-web/#bundling
* https://github.com/CoderLine/alphaTab/issues/759
* https://github.com/CoderLine/alphaTab/issues/699
* https://github.com/CoderLine/alphaTab/discussions/1098
* https://github.com/CoderLine/alphaTabSamplesWeb/tree/feature/webpack

Looking at the error, this seems rather a problem in your general project setup. No bug in alphaTab. Either your test server configuration is not serving those files correctly, or you the path is generally wrong so that no data is provided by the web server. I recommend you check your browser developer tools whether all files like fonts, and alphaTab worker files are packed and loaded 

https://stackoverflow.com/questions/30442319/failed-to-decode-downloaded-font

Feel free to reopen the issue if you are sure your general project setup is correct and the problem is really something in alphaTab.
