### ISSUE TITLE
Keep screen on while playing

### ISSUE THREAD

**Issue by LeadGuitarMx** [CoderLine/alphaTab#118]
On tablets or smartphones when you're playing a guitar tab the screen turns off.

I thinks this can be useful for the player, be able to keep the screen on.

I read about two possibilities:
- "I think there is another way doing it without any java code. You can add a video of 1 second with infinit repeat and hidden and it will do the trick. I have read it somewhere but i dont remember where.

IT WORKS!"

Or maybe usign this:
https://github.com/richtr/NoSleep.js

I don't know if this are good options or if you have a better way to do it.. but thank you very much for any help. : )

**Comment by Danielku15** [comment]
I'm not sure if this should really become part of alphaTab itself. Since there are already dedicated frameworks like NoSleep.js to do this, I would simply add those to your site instead of bringing that into alphaTab. 

If there would be a simple dedicated API to call I would add it of course. But shipping such a workaround solution seems a bit out of scope.
