### ISSUE TITLE
Grace note overlaps with the previous note

### ISSUE THREAD

**Issue by Reiji777** [CoderLine/alphaTab#1210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The grace note is unnecessarily overlapping with the previous note, though the bar still has room to display the notes properly. 

I found a similar issue (#1094), but seems the bug persists after the fix. 

<img width="558" alt="Screenshot 2023-07-03 at 9 53 45 AM" src="https://github.com/CoderLine/alphaTab/assets/41455097/6f242a5a-b9fb-469e-a8a8-b7ccfa2e69ac">

### Expected Behavior

The grace note shouldn't overlap with the previous note.

### Steps To Reproduce

It can be reproduced by uploading the tab to the demo player on alphatab.net 

Please find attached the example gp file for reference.
[grace-note.gp.zip](https://github.com/CoderLine/alphaTab/files/11931964/grace-note.gp.zip)

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
- **OS**: MacOS
- **Browser**: Chrome 114.0.5735.198
- **.net Version**:
```

**Comment by Danielku15** [comment]
What exact version of alphaTab are you using? I cannot reproduce your shown example in either 1.2.3 (released) and 1.3.0-alpha.684. 

1.2.3 (page layout) - tested on alphatab.net
![image](https://github.com/CoderLine/alphaTab/assets/674916/6617df4a-9d05-4d65-89a0-1182a24beee6)

1.2.3 (horizontal layout)
![image](https://github.com/CoderLine/alphaTab/assets/674916/9542a028-a66e-4e72-bb64-bb0513074095)

1.3.0-alpha.684 (page layout) - tested on next.alphatab.net
![image](https://github.com/CoderLine/alphaTab/assets/674916/fc8cbd47-302c-4b98-b427-ab18197fdbd6)

1.3.0-alpha.684 (horizontal layout)
![image](https://github.com/CoderLine/alphaTab/assets/674916/23bcbf9f-4f69-4e22-97e7-64152b12dc35)

**Comment by Reiji777** [comment]
I wrote a simple script to demonstrate the issue. I'm using the version alphatab@1.3.0-alpha.684

https://stackblitz.com/edit/web-platform-8bu4vd?file=index.html

The issue happens when the screen width is small (e.g. 300px). For example, in the second line of the following screenshot, the grace note has overlapping issue; the third line doesn't have any display issue while having the same amount of notes.

<img width="289" alt="Screenshot 2023-07-03 at 10 35 47 PM" src="https://github.com/CoderLine/alphaTab/assets/41455097/13e7eec2-f6ff-454a-b6a4-adf5aa5586fe">



When there's enough width, the overlapping issue won't occur.
<img width="506" alt="Screenshot 2023-07-03 at 10 19 35 PM" src="https://github.com/CoderLine/alphaTab/assets/41455097/38f77955-fd94-4c61-a0c3-6bf8a11deb81">

**Comment by Danielku15** [comment]
This is the expected behavior. If there is simply not enough space for the notes to be placed, there must be overlaps.  For each note a minimum size is calculated it requires. This size then influences the general spacing in the bar according to the time they are played (in a more-or less logarithmic scale). According to this notes are then placed. Grace notes are treated special: they are "sticking" to the next note following them. 

There is always room for improvement (especially with grace notes) but I prefer not to touch this area currently unless it is really a misbehavior. In this case we could try adding a mechanism which would prefer a correct time position but rather avoid collisions. Not a straight forward thing. 

For such small sizes I would recommend to switch to horizontal layouts or reduce the scale dynamically.
