### ISSUE TITLE
Sound font question

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#123]
Could you recommend a better sound font for player? Have you any experience in this topic, or should I google more? I tried few sound fonts, but I could not find better

**Comment by Danielku15** [comment]
I made the best experience with the default soundfont that comes with alphaTab. It does not sound the best but has a reasonable size to download. [Musescore ](https://musescore.org/en/handbook/soundfont)has a really nice soundfont (Fluid R3) but it's quite big in the SF2 format. The FluidR3Mono_GM.sf3 would be great in size and quality, but alphaSynth does not support SF3 (ogg-vorbis compression) so far. I started looking into this but decoding ogg-vorbis to raw PCM samples is a nightmare since I cannot use libvorbis (C library) . 

I also thought of supporting mini-sf2s or SFZ for more flexible loading of only individual instruments. If you only need 5-12 instruments, higher quality soundfonts would be still feasable to download. It's not directly on my roadmap but somewhere in the back of my mind :smile:

I've also experienced that not all SF2 soundfonts are always played as expected. If you found a dedicated SF2 you'd like to use, but experience issues with it, let me know so I can look into this dedicated problems.

**Comment by gburlet** [comment]
Better quality sound fonts are nice, sure, but I don't think it has a place on the critical path. AlphaTab is a music engraving library whose primary purpose is to engrave sheet music. Maybe this is a feature request for AlphaSynth, but even then I'm not sure it belongs on the crit path. Just my opinion; @Danielku15's the big boss.

**Comment by Danielku15** [comment]
I consider this discussion as closed. AlphaTab 1.0 will ship with a Sonivox based soundfont and with the new TinySoundFont based synth quite a bit more soundfonts are supported better. 

Feel free to reopen if needed. There are other issues tracking improvements like to support multiple soundfonts and SF3.
