### ISSUE TITLE
When playing for the second time to the end, it cannot be stopped and emits a harsh noise.

### ISSUE THREAD

**Issue by goodgame365** [CoderLine/alphaTab#1298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I found a serious bug. When playing from the beginning to the end for the first time, and then playing from the beginning to the end again, there is a continuous noise that cannot be stopped. I don't know what the problem is.

https://github.com/CoderLine/alphaTab/assets/17884664/d9ccf138-6a38-4fbb-a49a-0b67155687cc

### Expected Behavior

I believe this is a bug and it can be reproduced. I hope it can be resolved!

### Steps To Reproduce

[t2.zip](https://github.com/CoderLine/alphaTab/files/13422418/t2.zip)

### Found in Version

1.3-alpha

### Platform

Web  javascript   

### Environment

```markdown
anywhere
```

**Comment by Danielku15** [comment]
The problem is caused only when alphaTab uses the "ScriptProcessorNode" instead of the "AudioWorklets". AudioWorklets are not available if:
1. AlphaTab is bundled with WebPack (webpack has only very limited audio worklet support, not compatible with alphaTab)
2. AlphaTab is used in a [non-secure context](https://developer.mozilla.org/en-US/docs/Web/API/isSecureContext)
3. The browser really doesn't support [AudioWorklets](https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletNode#browser_compatibility)

On alphaTab.net rule 1. applies. 


And the root cause seem to be an inconsistency in the time calculation. For this file (only on the second round) the "tick position" indicates that the player has not yet finished, but the "time position" marks the file as finished. 

There must be somewhere an inconsistency in the reporting of played samples. Maybe some samples from the previous playback are still in the buffer and played additionally leading to a wrong calculation on the positions.

**Comment by Danielku15** [comment]
Update: I could now reproduce it also on the AudioWorklets.

**Comment by goodgame365** [comment]
> Update: I could now reproduce it also on the AudioWorklets.

I found a temporary solution, which is to add a stop() method when he plays to the end and there is no set to replay, forcing it to return to its initial state.


\playground\control.js
-------------------------------------
 at.playerPositionChanged.on(function (args) {
      ...   ....

        //Add new code here.
        if (!at.isLooping && args.currentTime === 0 && args.endTime > 0) {

            at.stop();
        }
    });
