### ISSUE TITLE
Support export to musicxml?

### ISSUE THREAD

**Issue by LYH8112** [CoderLine/alphaTab#131]
# Your environment

* Version used: lastest
* Platform used:  C#
* Rendering engine used: GDI
* Browser Name and Version: 
* Operating System and version (desktop or mobile): windows 10
# Expected Results

How to export to Musicxml？ 
How to play like HTML5?

**Comment by Danielku15** [comment]
AlphaTab does not have any modules for exporting MusicXML. Since alphaTab is rather a viewer than a writer of music notation, thats why I currently have no focus on exporting capabilities. If you like you can write your own exporter. Just take a look at the model classes of the AlphaTab.Model namespace, the structure should be quite easy to understand.

The C# version also does not have the player functionality directly integrated, its on my list but the priority for it is rather low since most people seem to be using the HTML5 version, not the C# version. You could either integrate alphaSynth or a third party midi player. The alphaSynth plugin of the JavaScript version should give a good indication how to integrate alphaTab with some midi component.  

I will close this issue and open a new one for the player support of alphaTab in the C# version.
