### ISSUE TITLE
After updating to patch commit b079e29, this error occurred：the cursor pauses at the end of each bar

### ISSUE THREAD

**Issue by goodgame365** [CoderLine/alphaTab#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sure, here's the translation: "When this sheet music is played, the cursor pauses at the end of each bar, possibly because it didn't consider the case of dividing two eighth notes into a triplet.

video demonstration here:
https://github.com/CoderLine/alphaTab/assets/17884664/37f3c2a5-57cb-45d5-86f6-e137066f40e5

when the score like :
![未标题-1](https://github.com/CoderLine/alphaTab/assets/17884664/d5f504d8-66af-4799-b417-819a0099bce3)

### Expected Behavior

Normal Playback

### Steps To Reproduce

1、updating to patch commit b079e29
2、down this gp
[t.zip](https://github.com/CoderLine/alphaTab/files/13797847/t.zip)

### Found in Version

1.3-alpha

### Platform

Other

### Environment

```markdown
Any browserany
```

**Comment by goodgame365** [comment]
This one is also
And it's a different situation
[Parisienne Walkways.zip](https://github.com/CoderLine/alphaTab/files/13798309/Parisienne.Walkways.zip)

**Comment by goodgame365** [comment]
This one is also
And it's a different situation
[Parisienne Walkways.zip](https://github.com/CoderLine/alphaTab/files/13798309/Parisienne.Walkways.zip)

https://github.com/CoderLine/alphaTab/assets/17884664/836f5f40-470c-40ef-956c-7be297c88c64

**Comment by Danielku15** [comment]
With the reported files I noted following bugs to be fixed: 

1. With the triplet feel active the start and end times of beats appear to get reported wrongly. Instead of the 8 beats we can see there are 10 slots/slices in the tick lookup. 
2. There is a bug in the logic handling finding the next visible "slice". It doesn't continue the search to the next bar. 
3. We need to handle incomplete and overfilled bars with special cases matching the playback generation.
