### ISSUE TITLE
more detailed documentation?

### ISSUE THREAD

**Issue by xplorld** [CoderLine/alphaTab#143]
For now we barely have any useful documentations.
e.g.,
Is there a config to hide tempos?
Is there a way to render a one-(long)-line SVG?
Is there a way to export SVG file on JS platform (I am trying to use it on iOS)?

A more detailed documentation would be appreciated.

**Comment by Danielku15** [comment]
Please use the issue template next time. See [here](https://github.com/CoderLine/alphaTab/blob/master/contributing.md) for more details. 

Now to your topic: 

For most of the features of alphaTab I try to provide examples. They should be the most obvious explaination for developers. 

More experienced developers are welcome to dig into the code. The settings are described [here](https://github.com/CoderLine/alphaTab/blob/master/Source/AlphaTab/Settings.cs), and the json mapping can be found [here](https://github.com/CoderLine/alphaTab/blob/master/Source/AlphaTab.JavaScript/Settings.cs#L100). 

I have started a better documentation regarding the settings of alphaTab but it is not yet ready to be published. Writing documentation is not as easy as it might sound in a first go. Especially since I'm working alone on this project I am typically lacking of time and motivation to write documentation. I typically end up with some samples that already show the functionality. 

When I am working on alphaTab I try to focus on getting the requested features added and bugs fixed. Anybody is invited to help me out writing some more docs. I'm happy about proposals which topics are most important to be documented. 

I'm not sure if you need answers for the particular questions you mentioned or if they are more an "example" what should be answered in the docs. Anyhow here are the answers:

**Is there a config to hide tempos?**
Currently there is no easy way to do so. The tempo is quite important for people to know how fast the music is played. I think it is quite an essential part of the music sheet like the time signature and clef. Feel free to enter a feature request for it. I'd like to hear the requirement behind this and how you expect the feature to work (does it only hide the first tempo? what if there are tempo changes?) 

**Is there a way to render a one-(long)-line SVG?**
There is the horizontal layout. Shown in the features demo:  https://demo.alphatab.net/features.html#layouts

**Is there a way to export SVG file on JS platform (I am trying to use it on iOS)?**
Yes, there are multiple ways to get the SVG. The easiest way to use alphaTab is definitly to use the the JQuery plugin or the `AlphaTab.Platform.JavaScript.JsApi` (the jQuery plugin is just a simple wrapper around it). AlphaTab will directly render the final SVG into the element specified. You might need to disable the *lazy loading* to make alphaTab not optimize the display with scrolling:

`$('#el').alphaTab({lazy:false}`

If you are using a hidden WebView this should work fine and you can read the final SVG from the DOM. 

If you want to run alphaTab in an embedded JS engine (JavaScriptCore), you need to directly utilize the `AlphaTab.Renderer.ScoreRenderer` which is the actual rendering component. I prepared a small example which loads a guitar pro file, renders the SVG. 

https://jsfiddle.net/danielku15/6n09psm2/

**Comment by xplorld** [comment]
thank you for your response!

**Comment by Danielku15** [comment]
I think all questions of this issue are answered, new documentation is in progress.
