### ISSUE TITLE
Issue with player position when using custom playback speed

### ISSUE THREAD

**Issue by j4kim** [CoderLine/alphaTab#144]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Chrome 59.0.3071.115
* Operating System and version (desktop or mobile): Windows 10

# Expected Results

Clicking in the score should set the cursor position (visually and in the sequencer) at the expected tick/time, no matter what is the current `playbackSpeed`.

# Observed Results

After a speed change, the click event makes the cursor and the playback position not stay consistent. 

I made a little sketch of what I've observed : [here](https://image.noelshack.com/fichiers/2017/26/4/1498731803-as-pos.png)

Here is a mathematical description of what seems to happen:  

    s = speed
    c = click position
    cursor position = 2 * c * s
    sequencer position = c * s

# Steps to Reproduce (for bugs)

1. Open the [player demo](https://demo.alphatab.net/player.html)
2. Change the speed to 50%
3. Click at the first beat of the 9th bar

# Possible Solution 

Due to the ratio between click position and resulting cursor position, I suspected there was somewhere a division/multiplication confusion.
After a few hours of debugging, I found a first mistake in `AlphaSynth.js`, in the `TickPositionToTimePositionWithSpeed` function, at [line 3689](https://github.com/CoderLine/alphaSynth/blob/master/Build/JavaScript/AlphaSynth.js#L3689). Here is a `*` where it should be a `/`.
So I replaced it and now the cursor position is set at the proper position. Great, but the playback position is still misplaced. I suspected there was another mistake in the [`Seek` function of the sequencer](https://github.com/CoderLine/alphaSynth/blob/master/Build/JavaScript/AlphaSynth.js#L3581), but I didn't find it.

I need the `as.get_TimePosition` and  `as.set_TimePosition` functions to be consistent in order to synchronise the score with a video. Apparently these functions are binded to the playback position. It works fine when using `speed=1` but I want to be able to change that speed.

Thank's a lot for the work you do and for considering my bug report !

Cheers!

Joaquim

**Comment by Danielku15** [comment]
Thanks for the detailed report. I was on holidays the last 2 weeks, sorry for the delayed answer. 

I changed how the playback speed is applied on the tick-to-time conversion. You assumptions on the calculations were correct, the things I changed are: 

- TickPositionToTimePositionWithSpeed uses now the division instead of the multiplication. The `MidiFileSequencer.Seek` method uses now the multiplication. 
- The Seek method of the sequencer applied the Playback speed twice (on the parameter and in the method itself)

On my tests all the combinations worked fine after that. I could seek to any bar on any playback speed having the correct cursor position and playback. 

Feel free to reopene the issue if you still observe any problems.

**Comment by j4kim** [comment]
Great, hope you had good holidays.

Thanks a lot, it works fine !

I have a few other issues/questions I want to submit you, I'll post them in the next days.
