### ISSUE TITLE
Question about the timePosition resolution in AlphaSynth

### ISSUE THREAD

**Issue by j4kim** [CoderLine/alphaTab#146]
# Your environment

* Version used: master branch
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome Version 59.0.3071.115 
* Operating System and version (desktop or mobile): Windows 10

# Expected Results

Is there a way to get a more precise result than `as.get_TimePosition()` ?

I don't know much about how the sequencer works, so tell be if there is no easy way to do this. However I imagine the timing must be very precise in the sequencer, so the get_TimePosition API call may not be the most precise.

# Observed Results

The precision is currently approximately 0.09 second. i.e if we call 100 times the `get_timePosition` method in a second, we'll have only 11 or 12 different values.

# What I'm trying to do

I'me building a metronome sound. What I've done is retrieving the `_tempoChanges` from the sequencer. I use that to construct an array with all the precise times where a click sound has to be played.
(By the way, here is what I've done to get the tempo changes: https://github.com/j4kim/alphaTab/commit/6f4eaffff0a0b0533eb9f3df38e9ca9c0e75bf6d, please tell me if there is a simpler way)
Then, I need to know where I am in the score to properly progam the next metronome sound (using `setTimeout` or `requestAnimationFrame`).
For the moment it works but the precision of the AlphaSynth time creates accumulative delay.
![metronome delay](https://image.noelshack.com/fichiers/2017/28/4/1499971500-clicks-and-as-time.png)
("retard" means delay)

# Possible Solution 

If there is no way, I will consider a solution using javascript's timestamp ([`performaces.now()`](https://developer.mozilla.org/fr/docs/Web/API/Performance/now)).

Of course I'm also listening to your advices if you have other ideas.

Thank's again for this amazing work !

**Comment by j4kim** [comment]
I've implemented the solution I mentioned and it works fine, so this issue is no longer a priority for me :)

**Comment by Danielku15** [comment]
Whenever alphaSynth passed the generated samples to the audio playback ([`ScriptProcessorNode.onaudioprocess`](https://developer.mozilla.org/de/docs/Web/API/ScriptProcessorNode) ) it updates the position and triggers the `alphaSynth.positionChanged` event. 

So this is the most precise position that alphaTab/alphaSynth knows.  The playback buffer is set to 4096 samples and with the default sample rate of 44100hz the latency between the timePosition and the actual playback should be around ~93ms (which is exactly what you calculated)

I used to utilize also the position of the audio context but synchronizing the time position of the audio context with all the features of alphaSynth (seeking, playback speed, tempo changes, buffering etc.) is a nightmare. That's why I fully rely on my own calculations of the position based on the samples. 

If you have a concrete solution based on the performance API I'd like to see it. Maybe I can adapt parts of it so you don't need a separate solution for it. 

From the issue itself it looks like you have a demand for a metronome. alphaTab can generate a midi track with metronome together with the normal midi messages for the audio. There are mostly settings missing to enable/disable the generation and playback of the metronome.

**Comment by j4kim** [comment]
I'm a little confuse with all the Web Audio API stuffs, I feel like it's still a bit too advanced for me. But I understood there is no (simple) way to get a more precise time.

I don't have a concrete solution, it's more like a workaround, but still, here is how I did. 
Instead of getting the time from alphaSynth at each metronome click, I get it once when the player is played, and then I program the next clicks using timeouts and I use `performance.now` to correct the error due to `setTimeout`. So I don't eliminate the delay (due to `as.get_TimePosition`), but I considerably reduce the delay variation.  
I've pasted the code on the comments of this commit : https://github.com/j4kim/alphaTab/commit/6f4eaffff0a0b0533eb9f3df38e9ca9c0e75bf6d
I also made a [not really more comprehensive animated sketch](https://image.noelshack.com/fichiers/2017/28/6/1500154018-output-yl69wp.gif), yes, I like sketches.

I think a metronome feature would be great, but for the moment I'll utilize my homemade solution, on which I have total control.

**Comment by Danielku15** [comment]
I see, this way I cannot improve alphaSynth out of the box. I played through several possibilities but could not find a good solution to get rid of the delays. 

In the latest commits I added a first version of the metronome and uploaded the new version to the [demo site](https://demo.alphatab.net/player.html). For now it generates the metronome using the "side stick note" of an additional percussion channel. It might be interesting to have a separate audio sample which is mixed along the other audio.

**Comment by j4kim** [comment]
Oh... wow! I should have told you about this earlier :sweat_smile:

Otherwise, I don't know exactly what you changed but a new problem occurs now with the mouse events: On the player demo, click somewhere to move the cursor, then play, the cursor goes back where it was.  
I'm not opening an issue for this as I think you can fix it quickly, should I ?

**Comment by Danielku15** [comment]
My bad. I forgot to handle the new metronome events at the silent processing needed for seeking. 😅  The problem should be solved now..

**Comment by Danielku15** [comment]
Closing this issue now.

**Comment by ice-blaze** [comment]
It's still in an experimental state but outputLatency is maybe the solution in the future https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/outputLatency

I also wanted to share this very good article about latency https://www.html5rocks.com/en/tutorials/audio/scheduling/
