### ISSUE TITLE
when it can support gpx?

### ISSUE THREAD

**Issue by zhouhuakang** [CoderLine/alphaTab#148]
# Your environment
Mac Myeclipse

* Version used: master branch 
* Platform used: JavaScript
* Rendering engine used: HTML5
* Browser Name and Version: Chrome 59.0.3071.115 65bit
* Operating System and version (desktop or mobile): macOS sierra
* Link to your project: 

# Expected Results

      I have changed the file name Canon.gp5 to TestGpx.gpx in feature.html,line 50 “<div id="alphaTabShowcase" data-file="files/TestGpx.gpx"></div>“， I want to show the .gpx  file completely,

# Observed Results

      But alphaTab only shows two lines of the TestGpx.gpx,not the complete tab to me 

# Steps to Reproduce (for bugs)

Explain here the exact steps how to reproduce the problem. Try to provide a
running sample showing the issue. If you have problem with a dedicated input file, 
please provide a download link or attach it to the issue. 
 
1.  [Test.gpx link  ](https://github.com/zhouhuakang/test)

2. 
3.  

# Possible Solution 
If you already know a solution to the problem please provide it here.

**Comment by j4kim** [comment]
gpx is already supported, all you have to do is specify the file in the data-file property.

     <div id="alphaTab" data-file="path/to/your/score.gpx">

and then,

      $("#alphaTab").alphaTab();

**Comment by zhouhuakang** [comment]
@j4kim Thanks!
But I have changed a .gp5 to gpx,it does can show some of the whole tab,but it is no complete!

**Comment by j4kim** [comment]
I can't help, but I think you should provide the problematic file and be more specific about the bug to improve the chances that the developer helps you.

**Comment by Danielku15** [comment]
Hi @zhouhuakang : Please try to update your issue with a concrete problem description. GPX is supported in general, but there is a huge list of features in GPX where not all are supported yet. If particular musical elements are missing, please list them with concrete examples for files containing them. 

From an issue with only a description like here I cannot infer what your problem is. That's why there is the issue template which is supposed to be filled out: What do you observe and what is your expectation? 

Without this information I am sorry to tell you that I will not be able to help.

**Comment by zhouhuakang** [comment]
@Danielku15 Thanks,I have updated this issue

**Comment by Danielku15** [comment]
There was a special construct in bar 8 where a rest beat is marked to have a brush effect. Looks like the brush downstroke applied to the second voice, is also applied to the first voice. This caused an error when rendering the brush glyph for the rest voice. The problem is fixed in the latest version.
