### ISSUE TITLE
Any way to use this without having guitar pro files end up in users cache?

### ISSUE THREAD

**Issue by sinewavemultimedia** [CoderLine/alphaTab#156]
I was wondering if there is a way planned to be able to use this without having the guitar pro files end up in the users cache. Maybe some server side rendering to a custom format or something. Or does it already have this type of option and I am missing it?

**Comment by Danielku15** [comment]
First of all please use the issue template, even if it is a simple question. The contributing guidelines highlight this. 

To your question: AlphaTab is available in 2 versions: .net and JavaScript. Both versions are capable of producing SVGs and Midi. Based on this you could build a server side rendering component that directly provides the rendered graphics to the clients. 

There is no "built-in" mechanism of doing this, as it is not a direct goal of alphaTab to provide a server side component for rendering music notation. AlphaTab is a component which can take certain input formats and produce rendered music notation, integrating this kind of component into a bigger architecture within their applications is up do the developers who use it.

If you are using a ASP.net it should be fair easy to setup a server side rendering. For JavaScipt you would need to give Node.js a try. The high level API focuses on usage in browsers, but the lower APIs should be fully compatible with node JS since the SVGs are rendered as text without the need of a DOM. 

I hope this answers your question.

**Comment by tumbleweed-t** [comment]
Check C# samples.
You can use mono on linux, simply execute SvgDump with your gpx file server side, and serve the svg to your clients.

**Comment by sinewavemultimedia** [comment]
OK thanks. It is something I will look into.
