### ISSUE TITLE
Problem with Firefox

### ISSUE THREAD

**Issue by Nadalsin** [CoderLine/alphaTab#175]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Firefox Quantum (Version 58.0)
* Operating System and version (desktop or mobile): Desktop Ubuntu 16.04

# Expected Results

I want AlphaTab to display and play a .gpx file on Chrome and on Firefox.

# Observed Results

When I use Chrome I have no problems but when I use Firefox, the reading is choppy.

# Steps to Reproduce (for bugs)
 
1. Load AlphaTab with the .gpx file attached at this issue
2. Play it

Thank you for reading me.
[should_i_stay.gpx.tar.gz](https://github.com/CoderLine/alphaTab/files/1744378/should_i_stay.gpx.tar.gz)

**Comment by Nadalsin** [comment]
Yes you totally understood what I wanted to explain. Thank you for your response, I'll search informations about performance's problem with Firefox on Ubuntu.

**Comment by Danielku15** [comment]
I lately read some details that it can happen often under Linux that Firefox is not using any Hardware Acceleration due to driver availability. Did it only happen to you or also to (if any) your customers? 
Maybe you can check on your machine some other web based projects that use a lot of graphical elements (maybe some games or 3d tech temos) and also web audio api. I guess also those other projects might not run very smooth. 

If such other projects run smooth, it might be worth to find out what makes alphaTab so different. Also it would be still interesting what exactly was problematic for you. If it was the rendering, the audio playback or maybe the cursor movement.

**Comment by Danielku15** [comment]
I did various tests with some local VMs and could not see any significant performance issues on the latest Ubuntu and Firefox. This means either FF did already a lot of performance improvemnets in the meanwhile or also the new version of alphaTab does not suffer anymore from certain stressful operations. 

I would recommend to upgrade to the latest versions and check if the issues still are appearing for you. Feel free to re-open this issue and provide more insights if the performance issues still appear for you. If so, please try to provide some performance profiles from your environment (https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler)
