### ISSUE TITLE
add ability to change playback speed

### ISSUE THREAD

**Issue by kaeverens** [CoderLine/alphaTab#188]
feature request, not a bug, so the questions in the bug template don't apply.

I'm making an online practice tool for myself, and need to be able to change the playback speed.

I found that the jQuery file jquery.alphaTab.alphaSynth.js has basic playback things, but nothing more indepth such as setting loop points, playback speed, etc.

I've hacked speed control in by adding this to the "methods" area:

```
    api.setPlaybackSpeed = function(element, context, speed) {
      var as = getAlphaSynth(element);
      as.set_PlaybackSpeed(speed||1);
    };
```

In your code, you can call that like this:
`at.alphaTab('setPlaybackSpeed', 0.8);`

**Comment by Danielku15** [comment]
> feature request, not a bug, so the questions in the bug template don't apply.

Yes it applies: 
https://github.com/CoderLine/alphaTab/blob/master/contributing.md#entering-feature-requests

As I do not know which version you are using, I assume you are using the JavaScript version of the master branch. 

>I'm making an online practice tool for myself, and need to be able to change the playback speed.

The Player (Advanced Usage) Demo shows that this feature is already available an how it can be used. 
https://demo.alphatab.net/player.html

> I found that the jQuery file jquery.alphaTab.alphaSynth.js has basic playback things, but nothing more indepth such as setting loop points, playback speed, etc.

Not all API capabilities are yet fully documented but mostly shown in the player demo. So far alphaTab supports: 
- Simple Looping https://github.com/CoderLine/alphaTab/blob/31925dd3abfe7909f1b840673f4d41e51e5bc3c9/Samples/JavaScript/player.html#L195-L205
- Adjustment of playback speeds https://github.com/CoderLine/alphaTab/blob/31925dd3abfe7909f1b840673f4d41e51e5bc3c9/Samples/JavaScript/player.html#L220-L224
- Defining the playback range. No programatic example is available, but it is part of the "selection" logic [here](https://github.com/CoderLine/alphaTab/blob/31925dd3abfe7909f1b840673f4d41e51e5bc3c9/Build/JavaScript/jquery.alphaTab.alphaSynth.js#L687)

> I've hacked speed control in by adding this to the "methods" area:

All API methods for the player are defined in the [jquery.alphaTab.alphaSynth.js](https://github.com/CoderLine/alphaTab/blob/master/Build/JavaScript/jquery.alphaTab.alphaSynth.js) file.

**Comment by jonleecraw** [comment]
I know the docs aren't complete, so I'd rather post this here than somewhere else as this is open (using the JavaScript build pulled from the current master as of this post).

For using the playback range API, the start and end points are defined as ticks. This doesn't translate very well to a bar of music (BPM and time signature are part of the math of determining how long a measure actually is). 

Is a tick supposed to equate to a millisecond in this case? A 120BPM 4/4 measure should take 2 seconds to play. However, this, doesn't play (and properly loop) a single 120BPM 4/4 measure:

```
var playbackRange = {};
playbackRange.StartTick = 0;
playbackRange.EndTick = 2000;

at.alphaTab('playbackRange', playbackRange);
at.alphaTab('loop', true);
at.alphaTab('playPause');
```

The observed behavior is the measure plays slightly past halfway through, then loops, but with a loop artifact after first play (the second time the playback range starts in the loop, it plays maybe 2-300 ticks of the beginning of the measure, *then* resets to tick 0 and starts the loop over. This repeats for all subsequent loops).

The expected behavior is a single 120BPM 4/4 measure looping, and hopefully looping accurately enough to use for practice.

This seems like a bug, but I may be using the API incorrectly and not understanding ticks in this context, so I thought I'd post here and get clarification before opening a bug.

**Comment by Danielku15** [comment]
As there was no answer, I'm closing this issue. Feel free to reopen if something is unclear.
