### ISSUE TITLE
AlphaTex Chord Names and Diagrams

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#203]
# Description 

**User Story**: As a user I would like to be able to specify a chord name above a chord using AlphaTex.
**User Story**: As a user I would like to show chord diagrams above the score using AlphaTex.

I use AlphaTex to create scores within AlphaTab. It looks like the above user stories work for GuitarPro import but not for AlphaTex import.

Regarding chord diagrams, I saw [this post](https://twitter.com/alphaTabMusic/status/828308020862009350) on the AlphaTab twitter indicating that some work has been done towards chord diagrams. I see that it is also on the 1.x release milestone, along with Issue #110, and Commit 2315547bf6c79fce810988d1295f88c6154033fd. Therefore, I realize it's currently in the pipeline. Would be great to be able to access the chord diagrams that currently exist in AlphaTab through the AlphaTex interface.

# Possible Solutions

Chord Names: AlphaTab seems to already have functionality to render a string of text above a beat, although not from AlphaTex. Create an entry in `AlphaTexImporter` that reads this information properly.

Chord Diagrams: In terms of possible solutions, it would be great if we could specify in the metadata portion of the AlphaTex which chord diagrams we would like to display. Maybe based on textual chord name as lookup, or maybe a more general text specification that outlines the name and composition of the chord diagram?

I think being able to display chord names above chords is the most important feature for the community and would require not too much work to accomplish. The second user story of chord diagrams is more involved in terms of implementation, I think.

# Current Workarounds 

None that I'm aware of.

# Bounty

@Danielku15, as usual it would be my pleasure to donate you a few beers for tackling this! If anyone else is interested in contributing I'd be happy to donate some beers their way as well. Thanks for making AlphaTab awesome.

**Comment by Danielku15** [comment]
Thanks for the comprehensive request.  I will quickly get the chord diagram rendering merged and then try to add some reasonable AlphaTex metadata parsing. Shouldn't be too much work.

**Comment by Danielku15** [comment]
Unfortunately this is nothing new and rather a missing feature than a bug. alphaTab does not support tied notes on non stringed instruments. For alphaTab a tied note is looking for a previous note on the same string. It works partly for MusicXML as it specifies somehow on which note ties start and stop. 

In your example it could assume that it is directly the note of the previous beat, but this might not be the truth. It could also be the note of the second beat the note is tied to. Same applies if you have multiple notes on the beats. 

If you want this working I recommend opening a feature request with your expected behavior for different combinations of notes. With the current feature set I can only offer to make the alphaTex parsing fail if you use tied notes on non stringed instruments.

**Comment by gburlet** [comment]
Actually, tied notes for non-stringed instruments (e.g., vocal music) was working after Issue #139. Commit 491d8b2d0ff0c94ddb4f0d451a8ab512e6f2afe4 specifically addressed the issue of tied notes in this context. I think linking the tie with the most recent beat of the same pitch makes sense and works for all my use cases.

I will close this issue and open a new one specific to this case. I'll let you determine whether to tag it as a bug or a feature request 👍
