### ISSUE TITLE
The render is not correct for Tie/Slur

### ISSUE THREAD

**Issue by lyh007045** [CoderLine/alphaTab#204]
The render is not correct for Tie/Slur.

# Your environment

* Version used: develop branch
* Platform used: C#
* Rendering engine used: GDI
* Browser Name and Version: 
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

# Expected Results
![musescore](https://user-images.githubusercontent.com/7369814/46952992-1d144a00-d0bf-11e8-97b2-e30d0b2e5818.png)

# Observed Results
![alphatab](https://user-images.githubusercontent.com/7369814/46953027-32897400-d0bf-11e8-89a9-358d106daf5c.png)

# Steps to Reproduce (for bugs)
1. open music xml file (TestMusicXml.xml)
2. modified "IsTiedBlend" function in GhostNoteContainerGlyph.  Else get error.
![code](https://user-images.githubusercontent.com/7369814/46953320-1f2ad880-d0c0-11e8-9fd8-37000e3b64f7.png)

[TestMusicXml.zip](https://github.com/CoderLine/alphaTab/files/2478845/TestMusicXml.zip)

**Comment by Danielku15** [comment]
The problem looks related to the MusicXML format which is not yet fully supported.

**Comment by Danielku15** [comment]
**Direct issue related:**
The wrong display was actually a missing feature, not a bug. What we have here is a "slur" not a "tie". Even though music theory wise the long line is a "tie" (because it connects 2 notes of the same height) it was annotated in MusicXML as a slur. 

AlphaTab was not capable of handling slurs from any note to another.  I decided to clean up the slur handling to support this scenario and the result looks then as expected: 
![image](https://user-images.githubusercontent.com/674916/48664285-b0fd7b00-ea9c-11e8-9281-905c984cc600.png)

**Just for documentational purposes:** 
As part of this I needed to clean the existing "slur" behavior which was used for combining hammeron/pulloff and legato slide notes. I hope I covered all scenarios that it still works correct. At least the testfile worked fine. 

GP: 
![image](https://user-images.githubusercontent.com/674916/48664310-0174d880-ea9d-11e8-9bb2-cd67ee063fdc.png)

AlphaTab:
![image](https://user-images.githubusercontent.com/674916/48664317-1a7d8980-ea9d-11e8-9d55-654abaf74627.png)

You might notice that alphaTab has some more slurs than GP. That's because GP tries to combine only start a new slur/tie at the time when it is needed. While the AlphaTab version looks more complete, the GP version looks cleaner. From a Music Theory perspective I'm not sure if the GP notation would be clear to everybody. On the otherhand the testfile is using quite some artificial notation that maybe is not even important to be covered.
