### ISSUE TITLE
Automatic scrolling when playing sheet music doesn't work in certain browsers or horizontal mode

### ISSUE THREAD

**Issue by chris-saunders** [CoderLine/alphaTab#205]
# Your environment

* Version used: (master branch + Dev branch)
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Safari 12.0, Android webView (Chromium), iOS UIWebView, iOS WKWebView
* Operating System and version (desktop or mobile): Android, iOS, Mac OSX (10.13.6)

# Expected Results
As the music plays and the seek bar goes offscreen the browser scrolls automatically to keep up

# Observed Results
In any browser with layout mode set to horizontal it does not scroll, and in the listed browsers above it will not scroll regardless of layout.

# Possible Solution 
It seems to work for chrome, both on mobile devices and desktops. May be a browser specific issue.

**Comment by Danielku15** [comment]
Thanks to BrowserStack I could make some tests on various devices and could identify the issue. The problem is that alphaTab by default scrolls on `document.documentElement` which is the `html` tag.

Various mobile browsers seem to not be able to scroll on `html` but need to scroll on `body` instead.  I also found [this blog post](http://blog.jonathanargentiero.com/jquery-scrolltop-not-working-on-mobile-devices-iphone-ipad-android-phones/) on that topic. Changing the scrolling to `document.body` fixes the issue.
