### ISSUE TITLE
Style SVG elements

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#213]
# Question 
Is it possible to style fill/stroke of SVG elements without editing source?

# Environment
JavaScript Developer branch

**Comment by Danielku15** [comment]
Currently there is no way to configure the style of the elements dynamically. Some color and font settings are already generalized but not yet configurable from outside. 

Is there a particular use case what you would like to change and why? Like styling a particular group of notation elements in a special way (e.g. all note heads red, stems green and clefs blue)? Or more on high level: staff lines white instead of gray, music elements in a light gray, texts in white?

The used colors and fonts are defined in the RenderingResources class. This level of configuration could easily be added to the settings level. 
https://github.com/CoderLine/alphaTab/blob/master/Source/AlphaTab/Rendering/RenderingResources.cs#L26

**Comment by nascent** [comment]
Hi Daniel,

Thank you for that information.

I was able to style all I have needed thus far, including note heads, stems, clefs and text as well as staves.

Feel free to close this or change to a feature request since it would be nice to have a CSS method available as opposed to editing source (which isn't difficult in any case).

Kind regards

**Comment by Danielku15** [comment]
In general it looks to me that you are rather having a feature request than a question. The answer to the question if styling is already supported today, is unfortunately no. If you have a need to style the elements I would kindly ask you to open a new issue with the feature request template and try to provide all necessary information to me that is needed to fulfill your request. 

As you hopefully can understand: I do not know what your goals are and from the the simple 1 sentence request I cannot derive what you would like to have changed in alphaTab to make styling easier. To make a useful feature (also for others) out of this request, it is important to me to understand what elements you would like to style and how you want to achieve this. Especially as alphaTab is not only available for the web, every feature needs to be designed the way it makes sense for all platforms. In general the overall idea sounds like it makes sense. 

I'm closing this question and hope for a more detailed feature request issue from you to continue the discussion.
