### ISSUE TITLE
Note heads are not highlighted on Bass Clef of Grand Staff, when AlphaTab is playing

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#216]
# Your environment

* Version used: (developer branch)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
* Link to your project: http://acousticremedy.com.au/alphatab1/

# Expected Results
Notes in Bass Clef of Grand Staff should be highlighted

# Observed Results
Notes in Bass Clef of Grand Staff are not highlighted when playing music

# Steps to Reproduce (for bugs)
Trigger playback and observe

1. Trigger playback
2. Observe bass, (left-hand of piano) notes are not highlighted in succession as music plays

# Possible Solution 
None known

**Comment by gburlet** [comment]
@Danielku15 This is the same issue I mentioned at the end of issue #207: [comment for your reference](https://github.com/CoderLine/alphaTab/issues/207#issuecomment-439651507). Seems that @nascent beat me to the bug report!

**Comment by chris-saunders** [comment]
I believe this is due to the .at-highlight class never being assigned to the second staff.
Further investigation shows that in the JS function cursorUpdateBeat the variable className is only ever the beats on the top staff.

I have created a JSFiddle to demonstrate the issue https://jsfiddle.net/rj63L2ey/5/
In the fiddle the top staff starts at b0, and the bottom staff starts at b15. className, which is used in the function to highlight elements only ever gets the beats for the top staff, 0-14.

**Comment by Danielku15** [comment]
Multi staff and track highlighting should now work as expected, please everyone give it a try and report potential issues. It's available on version 0.9.6.284
