### ISSUE TITLE
Triplets are not merging correctly when note duration changes

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#222]
# Your environment

* Version used: 0.9.3.159
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox 64.0.2
* Operating System and version (desktop or mobile): ArchLinux
* Link to your project: https://www.theguitarlickdatabase.com

# Expected Results
Given the following alphatex:
```
\tempo 140 . \ts 4 4 :8 7.3{b (0 4)}{tu 3 sd} 5.2{tu 3 sd} 5.1{tu 3 su} 8.2{h}{tu 3 sd} 5.2{tu 3} 7.1{tu 3 su} :16 5.1{h}{tu 3 sd} 6.1{h}{tu 3} 5.1{tu 3} :8 8.2{tu 3 sd} 5.1{tu 3 su} 8.2{h}{tu 3 sd} 5.2{v}
```
The result should be (as rendered by Guitar Pro 6):
![triplet-bug-gp](https://user-images.githubusercontent.com/46634000/51078397-b77f2c00-16b4-11e9-93af-6c01325bd738.png)

# Observed Results
The tab produced by alphatab:
![triplet-bug-alphatab](https://user-images.githubusercontent.com/46634000/51078410-cebe1980-16b4-11e9-94cb-aa985eb13e0e.png)
Live example here: https://www.theguitarlickdatabase.com/lick/3
Another one: https://www.theguitarlickdatabase.com/lick/4

# Steps to Reproduce (for bugs)
Create a tab with the following alphatex code:
```
:8 0.1{tu 3} *3 :16 0.1{tu 3} *3 :8 0.1{tu 3} *3
```

**Comment by Danielku15** [comment]
Thanks a lot for reporting this issue: I am currently quite busy in private and do not have a lot of time for alphaTab. I will try to investigate on this issue soon. In general it seems related to the correct beaming of notes, I need to do check in more detail how Guitar Pro handles the beaming.

**Comment by Danielku15** [comment]
I pushed some changes regarding tuplet handling to the `develop` branch. This should bring the expected behavior in properly written music notation. 

AlphaTab tries to detect that tuplets are full and places the beams according to that. I couldn't fully find out how Guitar Pro handles this, but it definitly behaves different in cases where the tuplet is not fully filled and also potentially if beats with different durations are mixed within a single tuplet group.

**Comment by cheap-glitch** [comment]
Nice, thanks a lot. This also fixed problems with some rarer tuplets like quintuplets and sextuplets.
