### ISSUE TITLE
Playback ignores grace notes at the very beginning of the score

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#226]
# Your environment

* Version used: 0.9.3-162
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox 64
* Operating System and version (desktop or mobile): desktop (ArchLinux)
* Link to your project: https://www.theguitarlickdatabase.com

# Expected Results
When the score opens on a grace note, the playback should start on that note.

# Observed Results
The player ignores the grace note at the beginning of the score, as is evident from the initial position of the cursor:
![screenshot_2019-01-21 lick 41 the guitar lick database](https://user-images.githubusercontent.com/46634000/51466752-363a3000-1d6b-11e9-8129-da0f8fb8fd55.png)

Live example here: https://www.theguitarlickdatabase.com/lick/41

# Steps to Reproduce (for bugs)

Create a tab with the following alphatex and play it:
```
1.1{gr}{h} 2.1
```

**Comment by Danielku15** [comment]
I believe this is not a bug, but a problem in the music notation you wrote. With `gr` you indicate a "before beat grace". Music timing wise this means your grace note is "stealing" some time of the previous beat and is finishes its play time shortly before the following beat. But if you place a "before beat grace" at the beginning of your score, there is no beat where the grace note could steal its duration from. So basically it might be played before the song starts and ends at time 0. Hence it is ignored in alphaTab. 

You will need to write your grace as "on beat" so that it can steal the duration from the following beat, or you need to introduce an additional bar with a rest in it.

**Comment by cheap-glitch** [comment]
You're right, my bad! I totally forgot there was two kinds of grace notes since the first type is almost always used by default. And since GP is more lenient and plays "before beat" grace notes even when they are at the beginning of the score, I thought of it as a bug. But putting those grace notes on the beat solves the problem, and musically it makes more sense too.
