### ISSUE TITLE
Some tuplets do not merge correctly

### ISSUE THREAD

**Issue by cheap-glitch** [CoderLine/alphaTab#233]
# Your environment

* Version used: 0.9.3.169
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Firefox 65.0.1
* Operating System and version (desktop or mobile): ArchLinux (desktop)
* Link to your project:

# Expected Results
Triplets (and other tuplets) should merge together.

# Observed Results
A bug has appeared in the latest build (0.9.3.169) where some triplets don't merge correctly. Given the following alphatex:
```
:8 5.3{tu 3}*3 5.3{b (0 2)}{tu 3} 5.3{b (0 2)}{tu 3} 5.3{b (0 2)}{tu 3}
```
Version 0.9.3.164 will render correctly:
![screenshot_2019-02-16 the guitar lick database](https://user-images.githubusercontent.com/46634000/52903794-2bb46e80-3223-11e9-844d-8bf515d43b66.png)
But 0.9.3.169 will produce this:
![screenshot_2019-02-16 the guitar lick database 1](https://user-images.githubusercontent.com/46634000/52903802-3ff86b80-3223-11e9-99f1-43d3bfcca224.png)
Quite strangely, the triplets do actually merge when they have a bend effect attached to them.

# Steps to Reproduce (for bugs)
Create a tab with the following alphatex in version 0.9.3.169:
```
:8 5.3{tu 3}*3
```

# Possible Solution

**Comment by Danielku15** [comment]
This bug is a side effect of the changes in #228 . If you apply the tuplet as "note effect" instead of "beat effect" it gets reset. If you write the following code it works (notice that the tuplet is after the multiplier): 

```
:8 5.3*3{tu 3} 5.3{b (0 2)}{tu 3} 5.3{b (0 2)}{tu 3} 5.3{b (0 2)}{tu 3}
```
![image](https://user-images.githubusercontent.com/674916/52904328-b187e800-322a-11e9-9d35-c20b566166ca.png)

Nevertheless I fixed the issue and ensured that the tuplet is not removed in case it is added in the note effects.
