### ISSUE TITLE
Second voice - collisions

### ISSUE THREAD

**Issue by yaras6** [CoderLine/alphaTab#355]
# Description 
This task is related with behavior described in this question #353 

Would be nice if library will detect collisions or alternatively second voice could have a class which allows me to make second voice more transparent.

![image](https://user-images.githubusercontent.com/25822217/80638992-a43ad000-8a61-11ea-9f30-f4d2acf92d0e.png)

# Possible Solutions
No idea.
# Current Workarounds 
No workarounds.

**Comment by yaras6** [comment]
@Danielku15 With this ticket, could you improve drawing rhythm for second voice as well? Bellow is collision example, and it will be great to make this line shorter, because it makes really hard to read the tab. Thanks a lot in advance.
![image](https://user-images.githubusercontent.com/25822217/81065029-1173b880-8edb-11ea-8beb-83aa5d6f593d.png)

**Comment by Danielku15** [comment]
Dev Notes: Thanks to the spring-rod model we follow in alphaTab it is guaranteed that 2 notation elements across voices will always be aligned one after another. In Guitar Pro we can see this: nicely in this comparison:
![image](https://user-images.githubusercontent.com/674916/103823574-a46c8000-5072-11eb-8695-6f71bbcddb29.png)

Note: on Guitar Pro the rods of rests seem to span 1 notehead width, not the rest glyph size. 
Explanation: On left the 3rd rest is before the 3rd note. To have enough space for the 3rd rest before the note the springs are stronger. It is guaranteed that 2 rods do not overlap because there is always a spring inbetween them and spring with force 0 has the width 0. On the right example, the 2nd rest is longer and the 3rd rest shifts after the 3rd note. 

So there is never the case that notation elements at 2 different time positions can overlap partially as one rods follows the next. First we need to check in alphaTab that this constraint is also valid and properly followed. It could break if we 'accidentally' allow negative spring constants. 

Having this pre-condition in place we can reduce the collision detection checks of rests to the elements of the exact same time position the rest is. Then things get a bit simpler as we can mark "lines" as used and just place the rest above/below the last used line based on some rules. 

The `AccidentalHelper` already holds the min-max lines on a beat base. We can additionally cache the lines on a time base. When placing the rest glyphs of secondary voices we can just check against this list and displace the rest accordingly to do not overlap.
