### ISSUE TITLE
Moving through the tab and selecting notes programatically

### ISSUE THREAD

**Issue by MDoder97** [CoderLine/alphaTab#401]
# Description 

Ability to move through tab by clicking a button, etc. click "up" button that makes the selector go to the start of the line upwards. Likewise for down, and etc left to go 5 notes left from the current one, and same for the right.

Ability to select certain amount of notes programatically, etc. selecting next 5 notes from the current one on a button click.

# Possible Solutions

I have been able to kind of simulate selecting by using api.playbackRange, but i'm not sure how to interpret ticks in count of notes, also i'm not sure how to make the actual range that's active get the selected color.

I am willing to contribute and hopefully get these features and more launched asap since i have free time for the next couple of weeks. Thanks! :)

**Comment by Danielku15** [comment]
Currently I would say this is out-of-scope for functionality of alphaTab. It would make sense if alphaTab would provide an editing functionality, but as of today a programmatical navigation between beats and notes is rather something specific to the app/website integrating alphaTab. 

Technically it can be achieved already with the information provided by alphaTab with the `includeNoteBounds` set to `true`, the `boundsLookup` will contain information about the position of each individual note. As the rendering of alphaTab happens in a "Web Worker" also most information is hidden in there. Theoretically alphaTab could also provide a more "on-demand" API for requesting some specific details instead of providing a fully filled lookup container which is quite expensive. Details about the bounds lookup can be found in the docs of the ScoreRenderer:

https://www.alphatab.net/docs/reference/scorerenderer/boundslookup/

Using the position information of the note bounds you will have to build an own cursor system which moves left/right/up/down depending on the rules you need. 

When it comes to the selecting though, it might be a bit different. you figured out correctly that you need the `playbackRange` which is specified in "midi ticks" of the song. To translate a beat to the corresponding tick, you can either use the raw information of the song model or the tick lookup. 
Here some reference links on that: 

**Logic of alphaTab regarding mouse clicks and the related playback range selection given a start and end-beat**
https://github.com/CoderLine/alphaTab/blob/10e3632bcccfdc34438f8cca97720698b83a912c/src/AlphaTabApiBase.ts#L926

**Basic details on how the data model is structured**
https://www.alphatab.net/docs/guides/song-details

**The property of the beat giving you the absolute start of a beat in midi ticks: `beat.abolutePlaybackStart`**
https://github.com/CoderLine/alphaTab/blob/10e3632bcccfdc34438f8cca97720698b83a912c/src/model/Beat.ts#L318

Theoretically I agree that it could make sense to have a more convenient API like `api.setPlaybackRangeByBeats(startBeat, endBeat)`. From what I hear you plan to make a kind of editor like GuitarPro where you can:

1. Navigate through the score with arrow keys (and subsequent modify some parts of the score) 
--> both are not yet provided via some API of alphaTab out of the box as alphaTab has no editor functionality, it is more focusing on viewing functionality as of today. You can try to utilize the BoundsLookup for that. the docs there are still a bit vague and you might need to read a bit the source to understand the structure and API. 
2. Select a range of beats (likely via shift+arrow keys) 
--> Possible via `playbackRange` and the tick information about the selected beats 


So on top of that you will need to build likely a custom "cursor" module which overlays alphaTab.

**Comment by MDoder97** [comment]
Hey, thanks for the insight. I managed to implement functions that go backwards and forwards through bars.

```
function next() {
    let currentBeat = player._currentBeat;
    while((currentBeat.nextBeat != null) && (currentBeat.nextBeat.voice.bar !== currentBeat.voice.bar.nextBar)) {
      currentBeat = currentBeat.nextBeat;
    }
    if(currentBeat.nextBeat != null) {
      let beat = currentBeat.nextBeat;
      player.tickPosition = beat.absoluteDisplayStart;
      player.cursorUpdateTick(player.tickPosition, false);
    }
  }

  function back() {
    let currentBeat = player._currentBeat;
    while((currentBeat.previousBeat != null) && (currentBeat.previousBeat.voice.bar !== currentBeat.voice.bar.previousBar)) {
      currentBeat = currentBeat.previousBeat;
    }
    if(currentBeat.previousBeat != null) {
      let beat = currentBeat.previousBeat;
      beat = beat.voice.beats[0];
      player.tickPosition = beat.absoluteDisplayStart;
      player.cursorUpdateTick(player.tickPosition, false);
    }
  }
```

Since everything is connected to previous and next of itself, i am able to find the differences in their bars here for example. I was thinking of applying the same logic to different staves, ie. implement moving down and up this way, this is convenient also for moving a certain amount of notes.

Can you comment if this is bad practice somehow, can this cause some damage in any way? Can i do any cleanup to remedy it if there is any?
Can this line `beat = beat.voice.beats[0];` maybe map to some other instrument that isn't a the begining of the bar maybe? This is also solvable with above logic i think.

**Comment by Danielku15** [comment]
> Can you comment if this is bad practice somehow, can this cause some damage in any way? Can i do any cleanup to remedy it if there is any?

It seems you're using functions which are not intended to be used by the public. As they are not officially part of the [documentation](https://www.alphatab.net/docs/reference/api), they might also change at any time. 

1. `cursorUpdateTick`
```js
player.tickPosition = ..;
player.cursorUpdateTick(player.tickPosition, false);
```
The call to `cursorUpdateTick` should not be needed. A change of the tickPosition should result already in an update of the cursor automatically. I entered #413 to fix this issue. 

Beside that the model handling seems fine. Until the bug is fixed you can keep the call as it is. I do not expect it to change soon but better remove it once #413 is closed and you upgraded. 

> I have also managed to implement selection hijacking those 3 functions and finding the lastBeat beforehand which is x amount of notes after the currentBeat.

The hijacking of the selection would be good if alphaTab would provide it out of the box. e.g. when setting the playbackrange actually the visual selection should also update. Then you could just set the playbackRange and the selection would align correctly to the beats. Currently it's a 1:1 down mapping to the player.  I added #412 to tackle this behavior. 

> Can this line beat = beat.voice.beats[0]; maybe map to some other instrument that isn't a the begining of the bar maybe?

This code will not jump across beats or even voices. Different instruments are on track level, voices are notes on the same instrument, but played with different durations.

**Comment by LeadGuitarMx** [comment]
Hello MDoder97, 
I tested your code and it works, but only when there is no Repeat bars 𝄇
When there is repeating bars the key arrows make the player jump randomly 🤔.

I think this function is essential for the player.
If you want to practice a song using alphatab It's annoying and a waste of time having to take the mouse, pause the player, click on a previous bar, and click again play. 
When with the arrows you can easily go back and move 🙂.

This and the play/pause with the space bar is cool and easy :)
```
document.body.onkeyup = function(e){
	if(e.keyCode == 32 && e.target == document.body){
		e.preventDefault();
		api.playPause();
	}
}
```
Anyways thanks so much to Daniel for all the hard work 💪 thanks mate

**Comment by Danielku15** [comment]
@LeadGuitarMx Good point with the repeats, forgot about this point. To get the true start tick of a masterbar respecting repeats you would need to use the (currently private) tick cache: 
```js
function getBeatAbsolutePlaybackTick(beat) {
  const realMasterBarStart = at._tickCache.getMasterBarStart(beat.voice.bar.masterBar.start);
  return realMasterBarStart + beat.playbackStart;
}
```

**Comment by Danielku15** [comment]
@MDoder97 Is there anything open from your side on this issue?
