### ISSUE TITLE
GP: Free text overlapping

### ISSUE THREAD

**Issue by nikolayrantsev** [CoderLine/alphaTab#402]
# Your environment

* Version used: master branch
* Platform used: JavaScript 
* Rendering engine used: SVG
* Browser Name and Version: Version 85.0.4183.102 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS 10.15.6 (19G2021)
* Link to your project: local

# Expected Results

Free text should be displayed without overlapping

# Observed Results

Free text displays with overlapping in certain locations
<img width="1030" alt="metallica" src="https://user-images.githubusercontent.com/59288233/93687201-89c2cb00-fac4-11ea-92e3-dc99be5b665c.png">

# Steps to Reproduce (for bugs)

1. Upload .gp5 example (attached) 
[Metallica - Nothing Else Matters (ver 5).gp5.zip](https://github.com/CoderLine/alphaTab/files/5250486/Metallica.-.Nothing.Else.Matters.ver.5.gp5.zip)

2. Observe the overlappings
  

# Possible Solution 

This is not the best example, but it's taken from the top 100 of UG. Lyrics added as Free text what is not correct, of course.  For most of the users this file -  it's okay. I've checked this file rendering in multiple desktop apps - all are looking good. 
Appreciate the fixing this, 
Thank you!

**Comment by Danielku15** [comment]
As of today I would rather claim that this is the expected behavior and not a bug. I fully agree that it is not looking as it should, but alphaTab has not yet any "collision detection system" which would try to avoid such overlaps. 

Even if the file would properly have specified the text as lyrics, I would still claim that the overlaps are not a bug as it is as per current intended alphaTab behavior. It would be a new feature request/improvement to ensure enough space is reserved for the lyrics of a beat. But this would rather result in very strange behavior here as some texts are meant to overlap to the next beat:
![image](https://user-images.githubusercontent.com/674916/93720290-5b0e2880-fb88-11ea-8eb1-bbbd5707ebe4.png)

Every music notation software has it's very own algorithms on layouting the score with spacings and sizings. as the file was written in Guitar Pro obviously the spacing of it will always fit unless a Guitar Pro 8 might change the algorithm significantly. I have to admit that MuseScore does quite a good job on detecting the lyics from the free text fields and this could be an interesting feature for alphaTab as well. It almost seems they try to detect lyrics from the free text and align it to the beats depending on some rules. From the inspector it gets more obvious as both syllables are having no x-offset, meaning that they are aligned to the corresponding beat. 
![image](https://user-images.githubusercontent.com/674916/93720355-c2c47380-fb88-11ea-858c-32042b5e4d0a.png)
![image](https://user-images.githubusercontent.com/674916/93720377-df60ab80-fb88-11ea-98a0-6ed36174e987.png)

If you tested "multiple desktop apps" it would be good to share some more deeper insight on what you observed. It might be tempting to claim that some visual disturbances are a "bug" but here we're more talking about a new feature which is able to handle free text as lyrics with corresonding spacings. This is a non existent feature. The plan was to collision detection and improving visual elements in [v1.2](https://github.com/orgs/CoderLine/projects)

**Comment by nikolayrantsev** [comment]
Hi Daniel, 
Thank you for the attention and deep review, 
Agree, let's put in the future backlog

**Comment by nikolayrantsev** [comment]
OK, found the cause of this:
```      
display: {
        stretchForce: 0.5,
      },     
```
I've changed the value to 0.5 (or any less than 1)
https://cdn.jsdelivr.net/npm/@coderline/alphatab@1.1.0-alpha.42/dist/alphaTab.min.js

It would be nice to have in the future as the enhancement, 
Thank you!

**Comment by Danielku15** [comment]
You can use now [beattextaslyrics](https://www.alphatab.net/docs/reference/settings/importer/beattextaslyrics) to enable the import of beat texts as lyrics following some basic parsing rules.

**Comment by nikolayrantsev** [comment]
Thank you so much!
