### ISSUE TITLE
Scrolling fast causes playback to drop in fps

### ISSUE THREAD

**Issue by MDoder97** [CoderLine/alphaTab#407]
# Your environment
VSCode
* Version used: 1.0.0
* Platform used: JavaScript
* Rendering engine used: SVG (default), HTML5 or GDI
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): Desktop

# Observed Results
After taking the scrollbar and scrolling fast or even scrolling fast with mouse scroll, tab drops in fps by alot to like 10-15fps.
I have only been able to reproduce this with default Canon Rock tab.

# Possible Solution 
Perhaps something to do with lazy loading of the tab notes.

**Comment by Danielku15** [comment]
Did you try to disable the lazy loading as a test? Can you still see the drop in FPS? Unfortunately the only function to detect whether an element is visible reliably (`getBoundingClientRect`) might also be quite expensive if the browser performs some re-layouting. 

I will need to see if I can compute this value in a more lightweight fashion, or compute the required values only once and check them during scrolling. The problem is the mix of multiple scrollbars that could be on the page which influence the visibility.

**Comment by MDoder97** [comment]
@Danielku15  upon further investigation, it appears scrolling fast has nothing t odo with it, just scrolling to the bottom so the whole tab is loaded. If i disable lazy loading, it's loaded from the start so fps is low at the start. Can you give me any directions where i can look to try and fix this?
