### ISSUE TITLE
Looping is not seamless

### ISSUE THREAD

**Issue by Reiji777** [CoderLine/alphaTab#410]
# Your environment

* Version used: 1.0.1
* Platform used: JavaScript
* Rendering engine used: SVG (default)
* Browser Name and Version: Chrome 86.0.4240
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: https://jsbin.com/budozuf/2/edit?html,output

# Expected Results

The looping is expected to be seamless, meaning there wouldn't be slight pauses between each loop.

# Observed Results

There's a slight pause (sometimes with a beep sound) between each loop, causing the looping not seamless.

# Steps to Reproduce (for bugs)

Here's a simple example to demonstrate the issue I'm trying to describe. 
https://jsbin.com/budozuf/2/edit?html,output

The example uses the same code as the tutorial: https://www.alphatab.net/docs/tutorial-web/player
1. Turn on Looping in the player
2. Play the tab
3. Notice when the tab finishes playing and before it starts over, there is a slight pause that causes the looping not seamless.

# Possible Solution 

N/A

**Comment by Danielku15** [comment]
I improved the looping mechanism in #420. On fast songs you might still experience a small delay but this latency can hardly be avoided. It comes from the fact that due to the looping alphaTab needs to re-start generation of the audio at the start position. This buffering might take some additional milliseconds. The new version tries to avoid some restart of the audio output, and keeps the playback smoothly going as good as possible.
