### ISSUE TITLE
Support Splitted Rendering in Horizontal Layout

### ISSUE THREAD

**Issue by Tails** [CoderLine/alphaTab#42]
![horizontallayout](https://f.cloud.github.com/assets/354312/2109139/67708bfa-8feb-11e3-964a-700f543f4661.png)

This is from the unedited demo.

I think it has something to do with memory allocation or a boundary error. It doesnt work when the Bar Count in the left pane is on -1. It works until around 150. higher than 150 (even though there are more bars) the canvas renders white. If you lower the number of stave types being rendered, the bar count can be raised again, suggesting something with memory.

**Comment by Danielku15** [comment]
The latest source supports line-wise rendering in the Page Layout. For the Horizontal Layout it will be a bit more tricky because we do not know the height until we rendered everything. 

Simply layouting everything first and then do a splitted rendering would be possible. but it would be more awesome to have a layout+rendering like in the Page Layout.
