### ISSUE TITLE
alphatex tuning piano notation is higher than it should be

### ISSUE THREAD

**Issue by sugizo** [CoderLine/alphaTab#449]
# Your environment

* Version used: alphaTab v1.0.1 (, build 2)
* Platform used: JavaScript 
* Rendering engine used: SVG (default)
* Browser Name and Version: Google Chrome Version 87.0.4280.67 (Official Build) (x86_64)
* Operating System and version (desktop or mobile): Darwin MacBookPro.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64
* Link to your project: https://sugizo.pythonanywhere.com/music/notation/form_score_in_notation

# Expected Results

https://en.wikipedia.org/wiki/File:Clef_Diagram.png

# Observed Results

![screen_shot](https://user-images.githubusercontent.com/2418295/101118999-ebeb9080-361c-11eb-9471-e28da88ebf46.png)

# Steps to Reproduce (for bugs)

1. use alphatex with : 
```
\tuning piano
.
:4 c4 d4 e4 g4 a4 c5
```

# Possible Solution 

the notation of c4 is higher than it should be, can compare with the result using alphatex and the correct one from wiki
both link and screenshot provided above

**Comment by Danielku15** [comment]
alphaTab should indeed respect the piano tuning for the display transposition. Note: The standard notation for Guitar is transposed by one octave. In your example file you change the tuning but not the "instrument" of the track. Currently alphaTex requires the instrument to be **not** a guitar, otherwise it transposes the file. 

This means as a workaround until alphaTab consideres also piano tunings for the display, you can change also the playback instrument and the notation will be displayed expected.
```
\tuning piano
\instrument piano
.
:4 c4 d4 e4 g4 a4 c5
```

![image](https://user-images.githubusercontent.com/674916/101278154-d19ae980-37b9-11eb-99b5-f3d9f730fbc9.png)

**Comment by sugizo** [comment]
you right, not put 
`\instrument piano `
when raised this issue, thanks

**suggestion** 
perhaps if it show the treble clef, it should work as is, mean, just the treble clef like used in every instrument
if default used in guitar it show the octave (8) under the treble clef, not sure this **octave clef** supported in Guitar Pro or MusicXML

**ref**
https://en.wikipedia.org/wiki/Clef#Octave_clefs

**Comment by Danielku15** [comment]
> The guitar is traditionally notated an octave higher than the actual pitch, presumably so it fits better on the stave. 
https://music.stackexchange.com/questions/101432/why-is-guitar-music-written-one-octave-higher
https://music.stackexchange.com/questions/85235/guitarpro-notes-displaying-one-octave-too-low

I am following the usual rules of guitar notes in alphaTab ;) If the instrument is a guitar it is notated one octave lower than the pitch compared to other instruments. 

I'm reopening this issue to track the task of also not transposing the notes if we specify the `piano` tuning

**Comment by sugizo** [comment]
no worries, aware about the guitar notated one octave lower, it's just symbolic using **clef octave** like on the wiki octave clef link above
for instrument number value on alphatex perhaps it refer to : 
https://en.wikipedia.org/wiki/General_MIDI#Program_change_events
isnt it ?

**tried** 
```
\instument guitar
\instument bass
```
output still same like piano, so when change with number provided from wiki general midi, it work as expected
perhaps can put some info about general midi number instrument info on documentation or alphatex example or link to wiki about the value
thanks

**Comment by Danielku15** [comment]
**regarding the octave clef:**
Using an octave clef would be wrong because it would then also mean for the guitar to transpose the notes one octave higher than normal. Unfortunately there is nothing like a guitar specific clef annotation to indicate the 1 octave shift specific to these instruments, hence we have to stick to the default ones and apply an additional transposition. 

**regarding the instrument names:** 
"guitar" or "bass" are not a valid general midi program name. If you use "Overdriven Guitar" or "Acoustic Bass" it works.
https://www.alphatab.net/docs/alphatex/metadata mentions to use a general midi instrument number or name. I also just added a more comprehensive documentation on the instrument and tuning behavior.
