### ISSUE TITLE
expose metronome click events

### ISSUE THREAD

**Issue by jacopomaroli** [CoderLine/alphaTab#450]
# Description 

I'm currently implementing a solution to improvise along backing tracks. I'd like to show in my UI metronome counting.
It would be awesome having events dispatched containing info like current tempo, current click in measure, total clicks in current measure etc...

# Possible Solutions

1) dispatching synth events when consuming this queue https://github.com/CoderLine/alphaTab/blob/master/src/synth/MidiFileSequencer.ts#L191
2) expose the aforementioned queue and we can infer the current metronome status from the midi tick

# Current Workarounds 

none as synthdata is buried in the worker :(

P.S. keep up the amazing work!

**Comment by Danielku15** [comment]
Sounds like a valid usecase. Unfortunately triggering an event when certain midi things happen is not so easy as expected:  
alphaTab pre-buffers the generated audio, at this time the midi events are dispatched, but not yet actually played on the audio output. 

So there needs to happen a mapping back from the actual current playback position and the events that are happening. The problem on this is that it might have quite a significant performance impact when this is constantly happening. 

I am thinking of an approach where I feed the "synthesize dispatched" midi events into a second "playback dispatch" queue. Then, when the actual audio playback advances, this queue could be used to signal which midi events have been actually played. There would be still a slight diffence due to some audio latency aspects but it should give quite a good approximation and avoid too much CPU cost. 

To avoid this overhead for people who do not need it, I will likely add a setting where it can be configured which midi events are actually signaled via event: Metronome, Normal Note on and off, Program Changes, Tempo Changes, Time Signature Changes, etc. 

This feature could also be beneficial for other kind visualizations.

**Comment by jacopomaroli** [comment]
sounds great, you also squeezed the task in the next version. amazing! :D

**Comment by Danielku15** [comment]
The new midi event listener feature is available in 1.2.0-alpha.100 (yeay, milestone number!)
Following APIs have been added:
- https://www.alphatab.net/docs/reference/api/midieventsplayedfilter/
- https://www.alphatab.net/docs/reference/api/midieventsplayed/
- https://www.alphatab.net/docs/reference/api/midiload/

Additionally I added a full guide on how to use it: https://www.alphatab.net/docs/guides/handling-midi-events
