### ISSUE TITLE
Black background in winforms

### ISSUE THREAD

**Issue by novaXire** [CoderLine/alphaTab#504]
I try to use alphaTab in a .net5 winForm app but the background of the Score is black, so nothing is visible.

### Observed Results
![image](https://user-images.githubusercontent.com/62011280/103950970-22e22400-513e-11eb-9328-a4927a19be1e.png)

### Steps to Reproduce
Just following the tutorial https://www.alphatab.net/docs/tutorial-net/viewport with some minor change because it's not a wpf app.

**Version**
- [x] 1.1

**Flavor**
- [x] .net 

**System**
.net 5, winforms

**Comment by Danielku15** [comment]
Could be a bit special to the WinForms control due to the lack of transparency in WinForms. Can you try setting the `Foreground` property of the control to White? It's a bit hidden and not nice to use but the `Foreground` of the `AlphaTabControl` is set as background of the inner layout panel. This actually might be a legacy and not needed anymore but let's see first if this fixes the issue for you.

**Comment by Danielku15** [comment]
I added a dedicated own property for the back color of the notation area.

**Comment by novaXire** [comment]
I confirm, set the ForeColor to White works.

I tried with BackColor before reporting the issue but not this one.
