### ISSUE TITLE
Audio Playback does not work in FireFox (any version)

### ISSUE THREAD

**Issue by sinewavemultimedia** [CoderLine/alphaTab#52]
Hello,

I have tested the audio playback in Chrome, IE 11, and Safari, the player feature works in all these browsers. It does not however work inf Firefox I tested across several different firefox versions and none of them worked. 
Is this a known issue?

**Comment by bythink** [comment]
Why can not paly on  mobile devices? such as iphone ipad ?

**Comment by Danielku15** [comment]
The player feature is supposed to work on every platform that either supports Flash or the Web Audio API. 
Check http://caniuse.com/#feat=audio-api to find out if your browser supports it. A live demo can be found at http://demo.alphatab.net/player.html

It's not yet fully tested on all devices since it's not yet a fully stable feature. My testing browser (Google Chrome Mobile on a Nexus 5) seem to play the audio too fast which leads to wrong cursor positions in some versions (like the latest one).

**Comment by Danielku15** [comment]
I tested the latest version on the latest FireFox version (desktop and mobile) and playback was working as expected. I will close this issue.
