### ISSUE TITLE
Build issue: Sharpkit

### ISSUE THREAD

**Issue by webprofusion-chrisc** [CoderLine/alphaTab#62]
Using the latest SharpKit and either VS2013 or VS2015 the following build error occurs:

Error   SK0000  Unable to cast object of type 'SharpKit.JavaScript.Ast.JsCodeExpression' to type 'SharpKit.JavaScript.Ast.JsInvocationExpression'. [C:\Work\GIT\ThirdParty\alphaTab\Source\AlphaTab\Environment.cs] 
AlphaTab.JavaScript C:\Work\GIT\ThirdParty\alphaTab\Source\AlphaTab\Environment.cs  43

Which is:
RenderEngines = new FastDictionary<string, Func<object, ICanvas>>();

Not sure if this is a bug in sharpkit or not.

**Comment by Danielku15** [comment]
This is a bug in SharpKit. When I moved from Salterelle to SharpKit I've experienced some issues with compiling alphaTab. As part of this I started to fix some parts of SharpKit and I also enhanced quite a lot of code. Sadly those changes never made it to the SharpKit main branch. 

Because of this alphaTab comes with it's own build of SharpKit. Based on Danielku15/SharpKit. In long term I'd like to move to DuoCode but they are currently lacking of some essential features that are required to ship AlphaTab with the same performance as now.

**Comment by webprofusion-chrisc** [comment]
Ah, I see. Have you tried submitting a Pull Request just for this issue? I've found Dan-el to be quite receptive in the past.

Hadn't heard of DuoCode, will check it out.

**Comment by Danielku15** [comment]
There wasn't a direct Pull Request to merge but I've been in direct contact with him via mail. Maybe I'll try to pull the latest SharpKit sources and make the required adjustments for the latest version to make it work with alphaTab. 

DuoCode is quite a new but interesting C# to JavaScript compiler platform. They use the Roslyn Compiler with a custom compiler backend which makes it very state of the art for C# development (C# 6.0). There are currently 3 main points which prevent me from using DuoCode: 

1. They don't support custom JavaScript code inlining like SharpKit does. AlphaTab uses it's own "FastList" and "FastDictionary" classes to gain a big performance boost.
2. They don't support generating auto-properties as fields. For each property currently a full blown backstore field + getter method + setter method logic is generated which costs a lot of performance. 
3. They require a separete mscorlib.js base library which is quite big. To keep alphaTab as lightweight as possible some additional effort would be required to keep alphaTab as small as it is now (which is already quite big in the JS world).

**Comment by webprofusion-chrisc** [comment]
As an aside, I've started work on a non-GDI WPF renderer for Universal Windows Apps - targeting windows 10. Not much to it, I'll share it with you one I've finished the ICanvas implementation.

**Comment by Danielku15** [comment]
Looking forward to that canvas implementation. Since WPF (+ Universal Apps) heavily rely on DirectX rendering the API for drawing images outside of the normal UI context is a bit complicated. I just stumbled over Win2D which seems to be a nice library to have a GDI like drawing API in the XAML world. 

Please keep me updated about your progress on the Universal App

**Comment by Danielku15** [comment]
On the develop branch I moved now to a compiler I made on my own. It translates the C# codebase to Haxe which then allows further translation to other platforms like JavaScript. 

Also there exists now a .net standard version of alphaTab which provides SkiaSharp as raster image renderer.

Closing this issue as it seems not to be relevant anymore.
