### ISSUE TITLE
TypeError: right is undefined

### ISSUE THREAD

**Issue by nascent** [CoderLine/alphaTab#648]
### Expected Results

AlphaTab should play, as normal.

### Observed Results

AlphaTab, does not play and produces an error, line in code is as follows:

let samples = left.length + right.length;

### Steps to Reproduce

Press play

Link to jsFiddle, CodePen, Project etc.: 

https://www.emotive.productions/notation/clergical-reprise/player/

### Further details

All versions above and including v1.3.0-alpha.125 do not produce sound.

v1.3.0-alpha.125 produces an error, all other aforementioned versions produce no error.

### Your environment

**Version**
- [ ] 1.3-alpha.125 and above

**Flavor**
- [ ] JavaScript 

**System**

Firefox (Windows 10)

**Comment by Danielku15** [comment]
Please double check really the latest version. #645 should have fixed this [already](https://github.com/CoderLine/alphaTab/commit/433cbf31d1ebe8c4518578554a4f20ccf30e5499#diff-42579372ccf29f1be62b21a85ff90ec34facb87b1bddd7cb367331f84930d27a). Considering this change I don't believe that this should be still an issue in alpha.127

**Comment by nascent** [comment]
Hi Daniel,

I was using alpha.115 and thought I would upgrade, which I do periodically.

I have updated the example, to v127 but the problem still persists in FireFox.

If it makes any difference, I am using a Service Worker in the website but that's about all I can say about the situation other than to add that once play is pressed, besides there being a delay in Chrome (Chrome does produce sound), I can click on individual notes in FireFox, with notes in the bass clef being highlighted as if the music is playing but alas it is not, and no error is shown, which is why I went as far as i could, i.e. to alpha.125.

Regards

**Comment by Danielku15** [comment]
v128 is in the pipe and should fix the output problems on Firefox. But there seem to be still cursor flickering issues I have to address separately. 

Regarding your long delay: It is your server which is really slow and has caching disabled. Every time a worker or a audio worklet again a download of the 1.8MB (unminimized) alphaTab starts. You might want to check your webserver settings to allow caching of the related files to speed up the playback: 
![image](https://user-images.githubusercontent.com/674916/129606531-e6bbfc96-fba8-4de1-b390-5f78d5302a71.png)

The script processor was feeling faster because the download of the file for the worker happened already on page load. But the audio worklet download only starts upon play. If nothing is cached, this causes a delay in playback start.
