### ISSUE TITLE
Any chance to build the code with mono?

### ISSUE THREAD

**Issue by mbektimirov** [CoderLine/alphaTab#80]
Hey Daniel, did you try to build alphatab on mac or linux with mono platform? I see a lot of visual studio related stuff in the project, how hard it will be to convert it to build scripts?

**Comment by Danielku15** [comment]
Hello. 
It strongly depends on which platform you want to compile. The .net Version of alphaTab should be compilable on mono if the WPF components are removed. The JavaScript version is a bit more tricky because of SharpKit being used for the compilation. Which IDE/Build tools would you like to use?

**Comment by mbektimirov** [comment]
I want to compile it on the mac with mono and use [Visual Studio Code](https://code.visualstudio.com/) as an IDE. I'm not interested in WPF target, only in Js one. I see that you have a custom SharpKit here which is strongly coupled with the code and project files. There is also actively maintained [Bridge.net](http://bridge.net/) project, you should consider this compiler as an open source alternative to outdated SharpKit.

**Comment by Danielku15** [comment]
Yes, I am currently investigating in Bridge.net and I already started to contribute to the project so it fits the requirements of alphaTab. Currently Bridge.net delivers a lot worse performance on alphaTab.

**Comment by mbektimirov** [comment]
Sounds good. Is there any way to put build steps out from visual studio specific files into sh script?

**Comment by Danielku15** [comment]
I gave it a try to compile AlphaTab in MonoDevelop in a first step but SharpKit breaks at several parts. The funny thing is that SharpKit internally uses Mono.Cecil and NRefactory. I'll have to dig a bit deeper to find out what happens there.

**Comment by Danielku15** [comment]
One update: The build works now using MonoDevelop. Tested on Ubuntu:

1. apt-get install mono-complete mono-develop npm 
3. npm install uglify-js -g
3. Get alphaTab and open AlphaTab.sln
4. Compile the new MonoDebug or MonoRelease configuration. 

I also updated the StartSamples script so it can be run on Linux systems. For compiling with Visual Studio Code I need to investigate further. They claim since 0.10 solution files are parsed but I could not get any compilation running yet. For compiling from the commandline you could utilize also xbuild which is the msbuild from mono.

**Comment by mbektimirov** [comment]
Thanks, I managed to install MonoDevelop and load sln project, but now I have this error with `MonoDebug` target:
```
.../alphaTab/Source/AlphaTab.CSharp/AlphaTab.CSharp.csproj: 
Error: Cannot copy .../alphaTab/Source/AlphaTab.CSharp/bin/MonoDebug/AlphaTab.xml to 
.../alphaTab/Build/CSharp/AlphaTab.xml, as the source file doesn't exist. (AlphaTab.CSharp)
```
I commented all `<DocumentationFile>` sections in `*.csproj` files but it didn't help.

**Comment by mbektimirov** [comment]
Ok, I found the right place to comment: `AlphaTab.CSharp.csproj`
```
<Copy SourceFiles="$(TargetDir)$(TargetName).xml" DestinationFolder="$(SolutionDir)\Build\CSharp" />
```

**Comment by Danielku15** [comment]
I'm copying the XML Documentation as part to the Build Directory so developers have the documentation available for intellisense. It looks like Monodevelop does not pick up the settings in all configurations. But I'm glad you got it running for you.
