### ISSUE TITLE
Translating MIDI effects from Haxe to C#

### ISSUE THREAD

**Issue by mbektimirov** [CoderLine/alphaTab#81]
Hi Daniel,
What is the proper way to migrate MIDI effects generation from Haxe to C#? I translated `makeBend` from `MidiSequenceParser.hx` as is and it works but not for all notes. I tested it on `Samples/JavaScript/files/features/Bends.gp5` file and first two bends was played well but the last has been stuck. As I know you changed notes model, maybe there is something another new C# stuff that should be migrated too?

**Comment by Danielku15** [comment]
Hi there. 
I did some reading on the pitch bend events of the midi specification and added the bend effect generation including some tests. The midi generation is correct and sounds exactly like in GuitarPro5. Currently alphaSynth seem to have an issue where the pitch bend events are not interpreted correctly .That's why the bend effects still sound strange. I'll file a bug on the alphaSynth project and try to fix it soon. 

Regarding midi generation in general and how to do the migration: I completely started from scratch by reading the specs and simplify the generation. Many effects are still outstanding as you can see from the MidiFileGenerator class. What I usually do is to check how GuitarPro exports particular effects to midi and try to emit the same messages to get the same sound.

**Comment by Danielku15** [comment]
Closed this issue in favor of #331 to tackle the missing slides. The bend generation and audio handling of bends already got many extensions and improvemnets so the initially reported problems should also be obsolete.
