### ISSUE TITLE
Dynamic score/midi creation directly via API

### ISSUE THREAD

**Issue by dreamzor** [CoderLine/alphaTab#87]
Hello! Is this possible to use API directly to add notes dynamically?

I'd like to generate the score both internally from the website and 'externally' from user actions (editor like in guitar pro, but much much simpler).
Indeed, there already is functionality for this which is used by Importers, but the usage seems quite verbose and difficult. I'm also not sure that it supports dynamic update and won't redraw it completely every time.
One way is to write my own simplified generator of gtp using some other library and then reload resulting files but it also doesn't seem very clean.

I'm also thinking of Exporter (analogous to Importer) to save modified Scores to guitar pro and/or midi files, but I suppose it requires a lot of work.
By the way, maybe it worth considering to support ABC notation?

Thanks for the nice tool :)

**Comment by Danielku15** [comment]
Hello. 
There are multiple ways to generate a score: 

1. Build the data model directly using the classes. 
This is indeed a bit verbose. You would need to create all model elements correctly which might be quite time consuming to do manually. 

2. Use AlphaTex 
AlphaTex was planned to be a simple text-format to write the music notation for AlphaTab. I just recognized that somehow the documentation about alphaTex is not available on the website anymore. 
See check this fiddle for a small demo: https://jsfiddle.net/erm8r2mj/

3. Use the JSON exporter importer
The `AlphaTab.Model.JsonConverter` class allows converting Scores from and to JSON. It's similar to building the data model directly but you can leave it up to alphaTab to do all the magic like linking the beats correctly. 

Currently alphaTab always need to do a complete rerendering of the full score. There are many aspects to handle with partial rerendering. One single beat that is added, might require a complete relayouting of the full score if a line break is required due to the new beat. If the score is not too big, the rendering is fast enough to display changes immediately. 

Regarding the exporting to Guitar Pro probably GPX is the easiest way to go. There the main representation is an XML. Serializing to GP5 might be a bit more tricky but also doable with enough knowledge about the binary structure.

**Comment by dreamzor** [comment]
Awesome, thanks for the reply, you are indeed right that I couldn't find AlphaTex examples anywhere :) 
It makes sense to just generate the AlphaTex code from the inside and feed it to the AlphaTab. 

What do you think of adding MIDI import/export? I see that there are nice classes for MIDI support (used in AlphaSynth) already so the export should be straightforward.

**Comment by gburlet** [comment]
@dreamzor @Danielku15 I reference the alphaTex documentation [here](http://demo.alphatab.net/old/). Seems like most of the structure has not changed.

**Comment by dreamzor** [comment]
@gburlet thanks a lot! i wonder why there isn't a link to that page anywhere because it's extremely helpful.

**Comment by Danielku15** [comment]
@gburlet: Thanks for the link. I knew I had it online somewhere. It might be a bit outdated but I'll try to get a new version online. There is no link because it's likely quite outdated. 

Midi export is supported. When using the player feature a midi file is generated and passed to the alphaSynth (the playback library). Import is rather tricky because in midi a lot of information is lost compared to the data model used by alphaTab (bars beats etc.) Everything needs to remapped into a structure that would match the dynamic midi playback. 

Regarding the contribution on Linux you can utilize Mono and MonoDevelop. We just lately had a talk about compiling alphaTab on Linux #80 . Simply install Mono and MonoDevelop, get the repo and compile the Mono* targets. 

I would have enough knowledge about the Guitar Pro file format to write an exporter for GP5 (Gp3 and Gp4 are not needed in my opinion). A Gpx exporter should be also doable. The container format they invented is very strange but I'd have to inverse my thinkin of this block extraction. Please file another feature request issue for the exporter. This way I have it on my roadmap.

**Comment by Danielku15** [comment]
A new and updated documentation about alphaTex can be found here: 
http://demo.alphatab.net/alphatex.html
