### ISSUE TITLE
AlphaSynth is stuck when playing at slower/faster tempo

### ISSUE THREAD

**Issue by mrcperello** [CoderLine/alphaTab#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The player/scrolling has severe hiccups on a specific GP file.

### Expected Behavior

Player and scrolling work flawlessly regardless of the playback speed selected.

### Steps To Reproduce

1. Open the file attached at https://alphatab.net
2. Enable count in
3. Change playback speed to 0,75 or any other speed different than 1x
4. First play sometimes it goes almost okay but the second time the player is fully un-responsive and broken

### Found in Version

1.2

### Platform

iOS (WebView)

### Environment

```markdown
- **OS**: iOS 15/16, macOS 12/13 WKWebview
- **Browser**: Safari Version 16.0 (17614.1.19.1.5, 17614)

(We see issues as well on Android (Chrome) and other browsers like Firefox and so on.
```

### Anything else?

**On our implementation**
We face issues when rendering the 3rd and 4th bars of the whole file.
![IMG_A5BD8544E36D-1](https://user-images.githubusercontent.com/19806046/181605703-39e95a23-05e1-44f6-bf9d-cd0535cc1700.jpeg)

The duration of the first bar duration but the consequent ones are correct (we play in loop multiple repetitions).

The bar duration based on tempo is:
At 60BPM: 4s
At 72BPM: 3.33s (1.2x)
At 48BPM: 5s (0.8x)

And the player has a different duration when setting the tempo to 72 or 48:
At 72BPM the first bar plays at 2.13s and then at 3.33s
At 48BPM the first bar plays at 7.16s and then at 5s

**On the AlphaTab website**
We cannot select to render only the 3rd and 4th bars so we render the whole file but still but we see some issues when changing the playback speed.
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/19806046/181606206-e34f0c1a-f764-4244-b40b-bccd50e304db.png">

The cursor gets stuck and the sound is silent.

⚠️We cannot reproduce this in any other exercise and we would love to understand what is the issue.⚠️

[Unresponsive-or-unexpected-playing-behaviour.gp.zip](https://github.com/CoderLine/alphaTab/files/9213170/Unresponsive-or-unexpected-playing-behaviour.gp.zip)

**Comment by Danielku15** [comment]
On the alphaTab website there is already 1.3 running. Here in the issue you mention that it is a problem of 1.2. Can you confirm that this is a problem on both versions? 
There has been a rework of that part in the player lately and it sounds suspicous that it has the same behavior in both versions.

**Comment by Danielku15** [comment]
The root cause is the internal sub-buffer handling when synthesizing the audio. The output typically buffers in a ring-buffer the synthesized audio and requests more if the buffer is getting again empty. If the output already requested enough buffers, it will not ask for more, even if it runs out of samples and this becomes a problem towards the end of the song (or the end of the count-in midi). 

In this case the count-in midi completes. And the synthesizer stops responding to the sample requests of the output leaving the output "hanging". It knows it has no samples left, but it also does not request more because it still expects some response to the requested blocks. When the synth switches then from the count-in midi to the actual song the output doesn't ask for samples anymore and the song never starts playing. 

This is now solved by responding from the synth to all requests with either proper audio samples or an empty buffer. This way the output never "starves" because it will continue requesting samples unless the player is really stopped and finished.

**Comment by mrcperello** [comment]
I am glad the issue was found and fixed. Yay! Is there any defined date for this to be released?
