### ISSUE TITLE
Repeat section ignores a selection that covers it partially

### ISSUE THREAD

**Issue by mxAlexG** [CoderLine/alphaTab#944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
When you select a playback range that partially includes bars from a repeating section and includes bars beyond this repeating section, the cursor returns to the start of the repeating section  after it finishes the first repeating round instead of the start of the playback range. 
[Peek 2022-08-21 14-47.webm](https://user-images.githubusercontent.com/105655048/185789565-17b08778-fd5d-4617-8bc8-4a165347f2d7.webm)

### Expected Behavior

I am not sure if this should be considered a bug, but probably should prioritize what the user intended rather than what the logic implemented dictates.

### Steps To Reproduce

1. User performs a playback range selection
  a. It should start within a given measure section
  b. It should also end outside this measure section
4. User initiates playback
5. When the cursor reaches the end of the repeating section, it moves to the start of the repeating section instead of the start of the playback selection start tick

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **Linux, Ubuntu**:
- **Brave, and others**:
```

**Comment by Danielku15** [comment]
Looks like an unhandled edge-case. I would make more sense to just jump back to the start of the selection in this case.

**Comment by Danielku15** [comment]
I was just thinking it a bit further and it likely seems a more tricky problem than initially expected. The generated midi file does not know anything about repeats, it does not exist in midi. Internally on repeats, all bars are generated individually on the timeline. 

So actually on the time-axis the bars before the selection are in the future and therefore "correctly" played after the repeat. When making such a selection for playback, we seek the playback to the first time such a bar is played.

A visual example:

![image](https://user-images.githubusercontent.com/674916/187042247-7ea8643d-c836-4359-bd28-d08b31929593.png)

As seen there, we would expect suddenly a different midi file to be played due to the selection and this is currently not feasable. The whole audio playback is currently built on top of a final midi file and the display of the cursor is just synchronized with the ticks back to the bar it represents. 

And those are only basic repeats, there are also more advanced repeats with Dal segno. 

I have checked some other software and there the behavior is: 

1. MuseScore: It doesn't support this limitation of only playing a sub-part. It starts at the selection start and then continues normally to the repeat start and then beyond the selection end. 
2. Guitar Pro: it fully disables repeats when you only play a subselection. Also in cases of repeats the playback just goes through the bars ignoring any repeat annotations
3. SoundSlice: Behaves like alphaTab. It jumps to the repeat start outside the selection. 
4. Flat.io: Doesn't support playing sub-parts. 
5. noteflight: Behaves like alphaTab. It jumps to the repeat start outside the selection. 

Therefore I would consider this as expected behavior and due to complexity-vs-effort I don't plan to change anything here. 

For some simple cases the logic might be clear, but imagining cases like the following indicates already that it is hardly possible to have a clean unified logic with limiting the selection like this: 

![image](https://user-images.githubusercontent.com/674916/187043184-1265bc1f-729e-4617-9f85-9afa1aebd6e0.png)

**Comment by mxAlexG** [comment]
Interesting insights. 
I personally think Guitar Pro's approach is the most natural , but the last case you showed with multiple repeating sections might break the intended flow of the song, so what you say seems reasonable I guess. 
The only thing I am kind of concerned about is whether the end user would recognize what is happening when the cursor goes out of the selection bounds. If they do, then I'd trust that they'll recognize that a selection must be set within the repeating section or outside it.
