### ISSUE TITLE
Inability to place the cursor on some beats upon clicking

### ISSUE THREAD

**Issue by mxAlexG** [CoderLine/alphaTab#959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This behavior occurs regardless of which voice the note/beat clicked falls under. Another observation is that they are notes belonging to the first staff (index 0). Only encountered with grand staff tracks- MusicXML format. 

I used the same file I provided with issue #949  ([here](https://github.com/CoderLine/alphaTab/issues/949#issuecomment-1229179246)) and from this:
https://musescore.com/user/13955466/scores/5244260

I provided screenshots (from file in issue #949) for better reference :
![image](https://user-images.githubusercontent.com/105655048/187053578-acaf70d1-2d1c-4568-b137-13f6567e4037.png)
![image](https://user-images.githubusercontent.com/105655048/187053611-3c1ee26f-0141-4dbe-ad9e-88d466e5f2c5.png)
![image](https://user-images.githubusercontent.com/105655048/187053628-b68ce80d-8d4a-483f-b27f-f56f4c4f2763.png)
![image](https://user-images.githubusercontent.com/105655048/187053656-73e0e050-6124-4b02-9980-ba8a9219ee32.png)
![image](https://user-images.githubusercontent.com/105655048/187053677-ab022831-a686-43e2-abae-d784f22a05c4.png)
![image](https://user-images.githubusercontent.com/105655048/187053740-1fb61393-83a4-45f1-93b7-7a20e3398370.png)
![image](https://user-images.githubusercontent.com/105655048/187053763-461dd4f4-874c-4929-83b7-bbf2e0961c92.png)

### Expected Behavior

The ability to place the cursor on any note.

### Steps To Reproduce

1. Hold the mouse with your hand
2. Move the mouse cursor over every note
3. Tap on the currently hovered over note
4. Repeat until you encounter instances where the cursor doesn't get positioned on a beat

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **Ubuntu**:
- **Brave Browser**:
```

**Comment by Danielku15** [comment]
For the normal notes it is indeed a bug. Seems like some consolidation logic which used to be there got lost. A temporary workaround: 

```js
api.postRenderFinished.on(_ => {
    const lookup = api.renderer.boundsLookup;
    lookup.finish();
    for (const staveGroup of lookup.staveGroups) {
        for (const masterBar of staveGroup.bars) {
            for (const bar of masterBar.bars) {
                bar.beats.sort((a, b) => a.realBounds.x - b.realBounds.x);
            }
        }
    }
});
```

The grace notes selection is by design: Those are "before beat" grace notes at the start of a bar. That means they are effectively played even before the bar 21 starts as part of the previous bar. 

Grace Beats are a nightmare in music notation because they are not aligned correctly according to their actual time they are played, but they visually "stick" to the next beat and "steal" their duration from the previous or nest beat: 
* There are "on-beat" grace notes which start when normally the beat afterwards would start and the normal beat is shortened by the grace notes in front of it stealing part of the duration. 
* Secondly there are "before-beat" grace notes, which are stealing their duration from the previous beat which is shortened. So if they are in the start of a bar, they are actually played within the previous bar. 

So when you click on those notes visually, alphaTab will seek to this bar and the first beat played within this bar. And this is after the grace notes. 

This makes mismatch in visual placement and audio playback make it close to impossible to handle it correctly. When clicking on your mentioned examples, the cursor would actually need to be placed somewhere into the previous bar close to the end to be visually correctly placed at the time they are played.
